package br.upe.secap.programacao;

public enum AreaEnum {
	TODAS, 
	CIENCIAS_AGRARIAS,
	CIENCIAS_BIOLOGICAS,
	CIENCIAS_DA_SAUDE,
	CIENCIAS_EXATAS_E_DA_TERRA, 
	CIENCIAS_HUMANAS,
	CIENCIAS_SOCIAIS_APLICADA, 
	ENGENHARIAS,
	LINGUISTICA_LETRAS_ARTES;
}
