UPDATE trabalho set email_corrigido='carolina.miranda@upe.br', titulo_corrigido='\"SÃO PAULO, A CAPITAL DO NORDESTE\": A CRIAÇÃO DE UM ARQUÉTIPO DO NORDESTINO.' WHERE id=3553;
UPDATE trabalho set email_corrigido='Vilela352@outlook.com', titulo_corrigido='“O POVO AQUI EM CIMA PEDE SOCORRO”: RESSALTANDO A VOZ DA FAVELA ATRAVÉS DA MÚSICA RAP COMO FORMA DE REIVINDICAÇÃO DE DIREITOS' WHERE id=3821;
UPDATE trabalho set email_corrigido='tamara.silva@upe.br', titulo_corrigido='A ALTERNÂNCIA ENTRE O FUTURO DO PRETÉRITO E O PRETÉRITO IMPERFEITO DO INDICATIVO EM CONSTRUÇÕES HIPOTÉTICAS DENTRO DO PORTUGUÊS FALADO EM TEREZINHA-PE ' WHERE id=3664;
UPDATE trabalho set email_corrigido='eduardo.mendonca@upe.br', titulo_corrigido='A ANÁLISE RETÓRICA COMO FERRAMENTA PARA INVESTIGAÇÃO DO CONTROLE HERMENÊUTICO DAS DECISÕES DO SUPREMO TRIBUNAL FEDERAL SOBRE A POSSIBILIDADE DE PRISÃO APÓS CONDENAÇÃO EM SEGUNDA INSTÂNCIA DOS ANOS DE 2016 E 2019' WHERE id=3610;
UPDATE trabalho set email_corrigido='brunnoengamb@gmail.com', titulo_corrigido='A ARTE CINEMATOGRÁFICA E O ENSINO DE HISTÓRIA: UMA EXPERIÊNCIA PRÁTICA' WHERE id=3523;
UPDATE trabalho set email_corrigido='sandy.emanoelly@upe.br', titulo_corrigido='A ATUAÇÃO DO PSICÓLOGO NO SISTEMA DE ADOÇÃO: REFLEXÕES À LUZ DA LITERATURA ACADÊMICA' WHERE id=3466;
UPDATE trabalho set email_corrigido='adriana.rib@outlook.com.br', titulo_corrigido='A CONSTRUÇÃO DE IDENTIDADES ÉTNICO-RACIAIS NOS LIVROS DIDÁTICOS DE HISTÓRIA' WHERE id=3463;
UPDATE trabalho set email_corrigido='larissa.araujob@upe.br', titulo_corrigido='A CONTRIBUIÇÃO DA OFICINA PEDAGÓGICA NAS AULAS REMOTAS DE MATEMATICA NO 1º ANO DO ENSINO FUNDAMENTAL' WHERE id=3623;
UPDATE trabalho set email_corrigido='Vilela352@outlook.com ', titulo_corrigido='A CONTRIBUIÇAO DA PEDAGOGIA HISTÓRICO CRÍTICA PARA A EDUCAÇÃO' WHERE id=3651;
UPDATE trabalho set email_corrigido='filipe.gbsilva@upe.br', titulo_corrigido='A CRISE DE EFICÁCIA DOS DIREITOS HUMANOS DAS PESSOAS EM MIGRAÇÃO SOB UM OLHAR ARENDTIANO' WHERE id=3474;
UPDATE trabalho set email_corrigido='luana.ferreiraaraujo@upe.br', titulo_corrigido='A DETERMINAÇÃO SOCIAL EM SAÚDE DA MULHER QUILOMBOLA A PARTIR DO OLHAR PARA A SAÚDE SEXUAL' WHERE id=3483;
UPDATE trabalho set email_corrigido='pollysilva165@gmail.com', titulo_corrigido='A EDUCAÇÃO NA REFORMA LUTERANA' WHERE id=3591;
UPDATE trabalho set email_corrigido='lucas.bhs_@hotmail.com', titulo_corrigido='A EFICÁCIA DAS NOVAS AÇÕES PREVENTIVAS DO COVID-19 COM ENFOQUE NA EDUCAÇÃO EM SAÚDE NA COMUNIDADE QUILOMBOLA DO CASTAINHO, GARANHUNS-PE' WHERE id=3495;
UPDATE trabalho set email_corrigido='emanuelaferreirajupi18@gmail.com', titulo_corrigido='A FALTA DE REPRESENTAÇÃO DE ESCRITORAS FEMININAS NOS LIVROS DIDÁTICOS DE LÍNGUA PORTUGUESA DO ENSINO MÉDIO' WHERE id=3785;
UPDATE trabalho set email_corrigido='maria.anjos@upe.br ', titulo_corrigido='A FORMAÇÃO DO PENSAMENTO JURIDICO CRÍTICO A PARTIR DA INFLUÊNCIA DA CONSTITUCIONALIZAÇÃO DO DIREITO CIVIL NO ESTUDO DOS COMPONENTES CURRICULARES DE REORIA GERAL DO DIREITO CIVIL E DIREITO DAS OBRIGAÇÕES ' WHERE id=3670;
UPDATE trabalho set email_corrigido='beatriz.bento@upe.br', titulo_corrigido='A IMPLEMENTAÇÃO DAS DIRETRIZES NACIONAIS PARA A EDUCAÇÃO EM DIREITOS HUMANOS NO ENSINO SUPERIOR JURÍDICO DO SERTÃO DE PERNAMBUCO' WHERE id=3677;
UPDATE trabalho set email_corrigido='lourdes.laryssa@upe.br', titulo_corrigido='A IMPORTÂNCIA DA ATENÇÃO PRIMÁRIA À SAÚDE FRENTE A VIOLÊNCIA CONTRA A MULHER NA PANDEMIA' WHERE id=3569;
UPDATE trabalho set email_corrigido='andersongoncalvesrc@gmail.com', titulo_corrigido='A IMPORTÂNCIA DA ESCULTURA DENTÁRIA NO ENSINO ODONTOLÓGICO' WHERE id=3758;
UPDATE trabalho set email_corrigido='bruna.santana@upe.br', titulo_corrigido='A IMPORTÂNCIA DA ESFOLIAÇÃO NA ROTINA DE CUIDADOS COM A PELE: UM RELATO DE EXPERIÊNCIA' WHERE id=3661;
UPDATE trabalho set email_corrigido='iandracamila11@gmail.com', titulo_corrigido='A IMPORTÂNCIA DA INTERATIVIDADE NA EDUCAÇÃO A DISTÂNCIA ' WHERE id=3521;
UPDATE trabalho set email_corrigido='2019102616@app.asces.edu.br', titulo_corrigido='A IMPORTÂNCIA DA TERAPIA DE FOTOBIOMODULAÇÃO NA PREVENÇÃO E NO TRATAMENTO DA MUCOSITE ORAL EM PACIENTES COM CANCÊR' WHERE id=3477;
UPDATE trabalho set email_corrigido='bruna.santana@upe.br', titulo_corrigido='A IMPORTÂNCIA DO ATLAS DE ANATOMIA HUMANA NO PROCESSO DE APRENDIZAGEM DE ANATOMIA HUMANA: UM RELATO DE EXPERIÊNCIA' WHERE id=3675;
UPDATE trabalho set email_corrigido='Mariaingryd77@gmail.com', titulo_corrigido='A IMPORTÂNCIA DO CIRURGIÃO-DENTISTA NO DIAGNÓSTICO DE VÍTIMAS DE ABUSO SEXUAL INFANTIL.' WHERE id=3559;
UPDATE trabalho set email_corrigido='iually.almeida@upe.br', titulo_corrigido='A IMPORTÂNCIA DO ESTUDO DA HISTÓRIA DA MATEMÁTICA NA FORMAÇÃO DOS PROFESSORES DE MATEMÁTICA' WHERE id=3763;
UPDATE trabalho set email_corrigido='emanueli.ferreiral@upe.br', titulo_corrigido='A IMPORTÂNCIA DO EXERCÍCIO DE UM OLHAR CRÍTICO AO SE DEBRUÇAR SOBRE A AVALIAÇÃO PSICOLÓGICA' WHERE id=3563;
UPDATE trabalho set email_corrigido='gloria.vaz@upe.br', titulo_corrigido='A INCIDÊNCIA DA PANDEMIA DA COVID-19 NA PRISÃO: UMA ANÁLISE ACERCA DAS ALTERAÇÕES NO PRESÍDIO ADVOGADO BRITO ALVES, EM ARCOVERDE-PE.' WHERE id=3622;
UPDATE trabalho set email_corrigido='milena.pontes@upe.br', titulo_corrigido='A INCLUSÃO NA EDUCAÇÃO INFANTIL : O ATENDIMENTO EDUCACIONAL ESPECIALIZADO EM TEMPOS DE PANDEMIA' WHERE id=3436;
UPDATE trabalho set email_corrigido='alice.felix@upe.br', titulo_corrigido='A INCONGRUÊNCIA ENTRE A RETÓRICA POLÍTICA E JURÍDICA SOB UM VIÉS PRINCIPIOLÓGICO DO ARTIGO 8° DA CLT REFORMADA' WHERE id=3706;
UPDATE trabalho set email_corrigido='renatapsuchoa@hotmail.com', titulo_corrigido='A MERCANTILIZAÇÃO DA EDUCAÇÃO: IMPACTOS DO ENSINO REMOTO EM TEMPOS DE PANDEMIA' WHERE id=3718;
UPDATE trabalho set email_corrigido='VITOR.ALMEIDA@UPE.BR', titulo_corrigido='A MODERNIZAÇÃO DO SISTEMA DE SEGURANÇA PÚBLICA: O USO DO RECONHECIMENTO FACIAL E SEUS DESAFIOS.' WHERE id=3550;
UPDATE trabalho set email_corrigido='jorgelric@gmail.com', titulo_corrigido='A MONITORIA ACADÊMICA NAS DISCIPLINAS DE FUNDAMENTOS FILOSÓFICOS DA PSICOLOGIA E FUNDAMENTOS PSICOLÓGICOS DA EDUCAÇÃO: UM RELATO DE EXPERIÊNCIA' WHERE id=3748;
UPDATE trabalho set email_corrigido='isadorabno@hotmail.com', titulo_corrigido='A NECROPOLÍTICA QUE OPERA FRENTE À ATUAL POLÍTICA DE DROGAS NO BRASIL' WHERE id=3705;
UPDATE trabalho set email_corrigido='hortencia.vitoria@upe.br', titulo_corrigido='A NOVA FACE DA RESISTÊNCIA QUILOMBOLA: DESAFIOS E PERSPECTIVAS DO COVID-19 NESSAS COMUNIDADES' WHERE id=3527;
UPDATE trabalho set email_corrigido='vitoria.pereiras@upe.br', titulo_corrigido='A PONTE UNIVERSIDADE-COMUNIDADE NA ORGANIZAÇÃO DA X SEMANA DA CONSCIENTIZAÇÃO DO AUTISMO EM GARANHUNS: UM RELATO DE EXPERIÊNCIA' WHERE id=3779;
UPDATE trabalho set email_corrigido='thatiany.ferreira@upe.br', titulo_corrigido='A PRODUÇÃO DE VÍDEOS DIDÁTICOS EM MEIO AS AULAS REMOTAS: UMA EXPERIÊNCIA DO PROGRAMA RESIDÊNCIA PEDAGÓGICA' WHERE id=3509;
UPDATE trabalho set email_corrigido='sr2864722@gmail.com', titulo_corrigido='A RELEVÂNCIA DA DIAGNOSE NA PRÁTICA DOCENTE: UMA ANÁLISE REALIZADA A PARTIR DA INTERLIGAÇÃO DA RESIDÊNCIA PEDAGÓGICA COM O ESTÁGIO SUPERVISIONADO II.' WHERE id=3680;
UPDATE trabalho set email_corrigido='Jhucyane.piresrodrigues@upe.br', titulo_corrigido='A SALA DE AULA COMO LUGAR DE RESISTÊNCIA: A IMPORTÂNCIA DO ENSINO DA LITERATURA AFRO-BRASILEIRA  ' WHERE id=3440;
UPDATE trabalho set email_corrigido='arlindotg1@gmail.com', titulo_corrigido='A SAÚDE MENTAL DA POPULAÇÃO PRIVADA DE LIBERDADE BRASILEIRA: UMA REVISÃO DE LITERATURA' WHERE id=3669;
UPDATE trabalho set email_corrigido='andersongoncalvesrc@gmail.com', titulo_corrigido='A SAÚDE MENTAL DOS PROFISSIONAIS DA ÁREA DA SAÚDE DURANTE A PANDEMIA POR SARS-COV-2' WHERE id=3636;
UPDATE trabalho set email_corrigido='matheusnrq@gmail.com', titulo_corrigido='A SEXOPOLÍTICA DO HIV E AIDS PARA HOMOSSEXUALIDADE' WHERE id=3704;
UPDATE trabalho set email_corrigido='eduardo.mendonca@upe.br', titulo_corrigido='A TENTATIVA DE IMPLEMENTAÇÃO DA ABORDAGEM INTERDISCIPLINAR ENQUANTO EIXO DE ENSINO NOS COMPONENTES CURRICULARES DE HISTÓRIA DO DIREITO E DE INTRODUÇÃO AO ESTUDO DO DIREITO' WHERE id=3568;
UPDATE trabalho set email_corrigido='andre.salvino@upe.br', titulo_corrigido='ABORDAGEM DO TABAGISMO NA GESTAÇÃO - UMA REVISÃO DE LITERATURA' WHERE id=3588;
UPDATE trabalho set email_corrigido='vitoria.pereiras@upe.br', titulo_corrigido='ABORDAGEM FAMILIAR NA ATENÇÃO PRIMÁRIA À SAÚDE NO CONTEXTO DA VIOLÊNCIA DOMÉSTICA E SUAS CONSEQUÊNCIAS' WHERE id=3786;
UPDATE trabalho set email_corrigido='wislayne.mirelly@upe.br ', titulo_corrigido='ABORDAGEM PROTEÔMICA DE ADESINAS DE STREPTOCOCUS SP.' WHERE id=3805;
UPDATE trabalho set email_corrigido='marinaisaltino93@gmail.com', titulo_corrigido='ABORDAGEM TERAPÊUTICA DE DENTE PERMANENTE AVULSIONADO: UM RELATO DE CASO CLÍNICO' WHERE id=3712;
UPDATE trabalho set email_corrigido='witassio.oliveira@upe.br', titulo_corrigido='ABORDAGENS DE ENSINO PARA FUNÇÕES E EQUAÇÕES POLINOMIAIS CÚBICAS NA EDUCAÇÃO BÁSICA' WHERE id=3448;
UPDATE trabalho set email_corrigido='vitoria.nascimento@upe.br', titulo_corrigido='ABORDAGENS PRÁTICAS DE ATIVIDADES PROFISSIONAIS NA MONITORIA DE PRÁTICA PROFISSIONAL IV (GEOMETRIA E GRANDEZAS E MEDIDAS) NO FORMATO REMOTO.' WHERE id=3796;
UPDATE trabalho set email_corrigido='joaopedrohas35@gmail.com ', titulo_corrigido='ABORDAGENS TERAPÊUTICAS PARA ANGINA DE LUDWIG ' WHERE id=3490;
UPDATE trabalho set email_corrigido='thamires.mendes@upe.br', titulo_corrigido='AÇÃO EXTENSIONISTA NO PROGRAMA DE INTEGRAÇÃO SAÚDE NA ESCOLA COM O CURSO DE PSICOLOGIA: UM RELATO DE EXPERIÊNCIA' WHERE id=3727;
UPDATE trabalho set email_corrigido='paulonunes14081996@gmail.com', titulo_corrigido='ACLS (SUPORTE AVANÇADO DE VIDA EM CARDIOLOGIA): SIMULAÇÃO REALÍSTICA E RECURSOS TECNOLÓGICOS' WHERE id=3617;
UPDATE trabalho set email_corrigido='laura.limas@upe.br', titulo_corrigido='ADOLESCÊNCIAS DO QUILOMBO: DELINEANDO OS MOVIMENTOS DE (RE) EXISTÊNCIA' WHERE id=3487;
UPDATE trabalho set email_corrigido='jvictor.souza@upe.br', titulo_corrigido='AGINDO OU ATUANDO? REFLEXÕES PRELIMINARES DE WALTER BENJAMIN  A CERCA DA VERDADE SOBRE O ESPETÁCULO DA HISTÓRIA' WHERE id=3818;
UPDATE trabalho set email_corrigido='gildoribeiro.pe@gmail.com', titulo_corrigido='AGROECOLOGIA NO SEMIÁRIDO BRASILEIRO: PRESERVANDO O BIOMA CAATINGA E CONVIVENDO COM AS MUDANÇAS CLIMÁTICAS    ' WHERE id=3552;
UPDATE trabalho set email_corrigido='iara.geisa@upe.br', titulo_corrigido='ALEITAMENTO MATERNO: CONHECER PARA ESTIMULAR E PRATICAR – UM RELATO DE EXPERIÊNCIA' WHERE id=3619;
UPDATE trabalho set email_corrigido='pauladelima334@gmail.com', titulo_corrigido='ALGORITMO DE INVERSÃO DE GAUSS-JORDAN: UMA DEMONSTRAÇÃO' WHERE id=3790;
UPDATE trabalho set email_corrigido='natalia.piresf@upe.br', titulo_corrigido='ANALISANDO A RELAÇÃO ENTRE A INTOLERÂNCIA À LACTOSE E A SÍNDROME DO INSTESTINO IRRITÁVEL: UMA REVISÃO INTEGRATIVA DA LITERATURA' WHERE id=3759;
UPDATE trabalho set email_corrigido='arthur.aquino@upe.br', titulo_corrigido='ANÁLISE CLÍNICA, HISTOPATOLÓGICA E IMAGINOLÓGICA DOS CASOS DE AMELOBLASTOMA EM UM HOSPITAL DE REFERÊNCIA: UM ESTUDO RETROSPECTIVO' WHERE id=3667;
UPDATE trabalho set email_corrigido='renatha.lima@upe.br', titulo_corrigido='ANÁLISE COMPARATIVA ENTRE A ASSISTÊNCIA EMERGENCIAL AO ACIDENTE VASCULAR CEREBRAL EM SERVIÇOS DE REFERÊNCIA DA MICRORREGIÃO DO PAJEÚ E AS DIRETRIZES NACIONAIS' WHERE id=3518;
UPDATE trabalho set email_corrigido='tomaz.vasconcelos@upe.br', titulo_corrigido='ANÁLISE DA ACESSIBILIDADE EM ESCOLA PÚBLICA NA ZONA URBANA DO MUNICÍPIO DE SÃO JOSÉ DO SABUGI-PB' WHERE id=3515;
UPDATE trabalho set email_corrigido='kagomesdantas@gmail.com', titulo_corrigido='ANÁLISE DA ATIVIDADE TOXICOLÓGICA E FARMACOLÓGICA DOS COMPOSTOS DAS FOLHAS DA SCHINOPSIS BRASILIENSIS RELACIONADA À ODONTOLOGIA: ESTUDO IN SILICO' WHERE id=3508;
UPDATE trabalho set email_corrigido='giovanna.guedes@upe.br', titulo_corrigido='ANÁLISE DA MORTALIDADE MATERNA E DA REDE DE ASSISTÊNCIA OBSTÉTRICA NA MACRORREGIÃO DE SAÚDE 2 DE PERNAMBUCO' WHERE id=3630;
UPDATE trabalho set email_corrigido='rebeca.amorim@upe.br', titulo_corrigido='ANÁLISE DA SÍFILIS GESTACIONAL E CONGÊNITA EM PERNAMBUCO, 2010 A 2019' WHERE id=3517;
UPDATE trabalho set email_corrigido='wanderson.gustavo1@hotmail.com', titulo_corrigido='ANÁLISE DAS AÇÕES ANTRÓPICAS SOBRE A DIETA NATURAL DE GONIOPSIS CRUENTATA (LATREILLE,1803) (CRUSTACEA, DECAPODA, GRAPSIDAE) NO LITORAL PERNAMBUCANO' WHERE id=3811;
UPDATE trabalho set email_corrigido='ariellms01@gmail.com', titulo_corrigido='ANÁLISE DAS POSSÍVEIS RELAÇÕES ENTRE MEDIDAS PROFILÁTICAS PRÉ ACIDENTE VASCULAR CEREBRAL, DÉFICIT NEUROLÓGICO E GRAU DE INCAPACIDADE' WHERE id=3638;
UPDATE trabalho set email_corrigido='jefferson.lins@upe.br', titulo_corrigido='ANÁLISE DAS POSSÍVEIS RELAÇÕES ENTRE SINTOMAS DEPRESSIVOS, PENSAMENTOS CATASTRÓFICOS E INCAPACIDADE FUNCIONAL EM PORTADORES DE DOR CRÔNICA MUSCULOESQUELÉTICA' WHERE id=3719;
UPDATE trabalho set email_corrigido='arthur.santosf@upe.br', titulo_corrigido='ANÁLISE DE UMA JUVENTUDE EM LUTA: PROCESSOS DE RESISTÊNCIA DE JOVENS INDÍGENAS' WHERE id=3807;
UPDATE trabalho set email_corrigido='hosanasantos35@gmail.com', titulo_corrigido='ANÁLISE DOS PROCESSOS CELULARES SOFRIDOS NO CLAREAMENTO DENTAL COM USO DE PERÓXIDO DE HIDROGÊNIO' WHERE id=3516;
UPDATE trabalho set email_corrigido='tomaz.vasconcelos@upe.br', titulo_corrigido='ANÁLISE EPIDEMIOLÓGICA DA COINFECÇÃO POR HIV E TUBERCULOSE NO ESTADO DE PERNAMBUCO NO PERÍODO DE 2015 A 2020.' WHERE id=3457;
UPDATE trabalho set email_corrigido='alessandraraysa123@hotmail.com', titulo_corrigido='ANÁLISE ESTATÍSTICA DOS RESULTADOS ENCONTRADOS NO PERFIL DO INSTAGRAM DO PROJETO DE EXTENSÃO BELEZAS DO AGRESTE DA UPE/CAMPUS GARANHUNS.' WHERE id=3475;
UPDATE trabalho set email_corrigido='anairesalbuquerque@yahoo.com.br', titulo_corrigido='ANEMIA HEMOLÍTICA AUTOIMUNE IDIOPÁTICA COM DISSIDÊNCIA CLÍNICO-LABORATORIAL' WHERE id=3642;
UPDATE trabalho set email_corrigido='natalia.nogueira@upe.br', titulo_corrigido='APLICAÇÃO DAS TECNOLOGIAS DE COMUNICAÇÃO E INFORMAÇÃO (TIC) NA EDUCAÇÃO GEOGRÁFICA' WHERE id=3791;
UPDATE trabalho set email_corrigido='carlamacedo129@gmail.com', titulo_corrigido='APLICAÇÃO DE METODOLOGIAS ATIVAS EM MONITORIAS DE ANATOMIA HUMANA NO CURSO DE MEDICINA: RELATO DE EXPERIÊNCIA' WHERE id=3635;
UPDATE trabalho set email_corrigido='weliaaraujo00@gmail.com', titulo_corrigido='APLICAÇÃO DOS JOGOS LÚDICOS COMO FERRAMENTA NO ENSINO DE BIOLOGIA: UMA PROPOSTA EDUCATIVA PARA TRABALHAR SERPENTES COM OS ALUNOS ' WHERE id=3601;
UPDATE trabalho set email_corrigido='vanessadsl19@gmail.com', titulo_corrigido='AS DIFICULDADES DE ACOMPANHAMENTO DOS PROCESSOS DE AQUISIÇÃO DA LEITURA E ESCRITA NO ENSINO REMOTO.' WHERE id=3437;
UPDATE trabalho set email_corrigido='eduardaoliveira.upe@gmail.com', titulo_corrigido='AS FUNÇÕES EXECUTIVAS E AUTORREGULAÇÃO EMOCIONAL DE ALUNOS E PROFESSORES' WHERE id=3557;
UPDATE trabalho set email_corrigido='anesio.marcilio@hotmail.com', titulo_corrigido='ASPECTOS DO CANDOMBLÉ NA OBRA MACUNAÍMA DE MARIO DE ANDRADEASPECTOS DO CANDOMBLÉ NA OBRA MACUNAÍMA DE MARIO DE ANDRADE' WHERE id=3616;
UPDATE trabalho set email_corrigido='joabserafim@upe.br', titulo_corrigido='ASPECTOS EPIDEMIOLÓGICOS DOS PACIENTES ACOMETIDOS POR ACIDENTES VASCULARES CEREBRAIS ADMITIDOS EM SERVIÇOS DE REFERÊNCIA DA MICRORREGIÃO DO PAJEÚ ' WHERE id=3586;
UPDATE trabalho set email_corrigido='bruna09082001@gmail.com', titulo_corrigido='ASPECTOS FISIOPATOLÓGICOS E MANIFESTAÇÕES CLÍNICAS DA FIBROSE CÍSTICA' WHERE id=3812;
UPDATE trabalho set email_corrigido='marina.nascimento@upe.br', titulo_corrigido='ASSISTÊNCIA PRÉ-NATAL DURANTE A PANDEMIA DA COVID-19: IMPACTOS E ESTRATÉGIAS' WHERE id=3644;
UPDATE trabalho set email_corrigido='anapgsilva2@yahoo.com.br', titulo_corrigido='ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL COMO ESTRÁTEGIA PARA IMPLANTAÇÃO DE HORTA ORGÂNICA' WHERE id=3773;
UPDATE trabalho set email_corrigido='sandro.duarte@upe.br', titulo_corrigido='ATENÇÃO À PACIENTES DA REDE PÚBLICA DE SAÚDE COM NECESSIDADE DE TRATAMENTO ENDODÔNTICO EM CASOS COMPLEXOS' WHERE id=3720;
UPDATE trabalho set email_corrigido='simaobatista133@gmail.com', titulo_corrigido='ATIVIDADE ANTIBACTERIANA DE MICRORGANISMOS ISOLADOS DO INTERIOR DE RESIDÊNCIAS DA CIDADE DE GARANHUNS NO AGRESTE DE PERNAMBUCO' WHERE id=3530;
UPDATE trabalho set email_corrigido='kagomesdantas@gmail.com', titulo_corrigido='ATIVIDADE ANTIFÚNGICA DOS EXTRATOS DA SCHINOPSIS BRASILIENSIS ENGLER' WHERE id=3507;
UPDATE trabalho set email_corrigido='marcia.souza@upe.br', titulo_corrigido='AUTORITARISMO NO BRASIL: UMA ANÁLISE ARENDTIANA DO AUTORITARISMO PÓS ELEITORAL' WHERE id=3745;
UPDATE trabalho set email_corrigido='lucas.dantas@upe.br', titulo_corrigido='AVALIAÇÃO ANATOMOFUNCIONAL DA LÍNGUA DOS BEBÊS AVALIADOS NO PROJETO DE EXTENSÃO “LÍNGUA SOLTA”' WHERE id=3641;
UPDATE trabalho set email_corrigido='fabio.andrey@upe.br', titulo_corrigido='AVALIAÇÃO BIOMECÂNICA DE DIFERENTES TÉCNICAS DE OSTEOSSÍNTESE PARA A OSTEOTOMIA LE FORT I' WHERE id=3716;
UPDATE trabalho set email_corrigido='jmaxbmarcelo2@gmail.com', titulo_corrigido='AVALIAÇÃO DA ATIVIDADE GASTROPROTETORA DA GALACTOMANANA EXTRAIDA DAS SEMENTES DE CASSIA GRANDIS ORIUNDAS DO AGRESTE DE PERNAMBUCO' WHERE id=3481;
UPDATE trabalho set email_corrigido='analuisa.silva@upe.br', titulo_corrigido='AVALIAÇÃO DA ATIVIDADE GASTROPROTETORA DO POLISSACARÍDEO EXTRAÍDO DAS SEMENTES DE MORINDA CITRIFOLIA ORIUNDAS DO AGRESTE DE PERNAMBUCO' WHERE id=3532;
UPDATE trabalho set email_corrigido='lucia.beatriz@upe.br', titulo_corrigido='AVALIAÇÃO DA EFICÁCIA DO GEL DA GALACTOMANANA EXTRAÍDA DAS SEMENTES DE CASSIA GRANDIS NA ROTINA DE CUIDADOS COM A PELE EM UM GRUPO DE VOLUNTÁRIOS DA UNIVERSIDADE DE PERNAMBUCO CAMPUS GARANHUNS ' WHERE id=3556;
UPDATE trabalho set email_corrigido='ERICKA.ALMEIDA@UPE.BR', titulo_corrigido='AVALIAÇÃO DA QUALIDADE DOS SERVIÇOS PRESTADOS A SAÚDE DA MULHER EM UNIDADES BÁSICAS DE SAÚDE NO MUNICÍPIO DE SALGUEIRO' WHERE id=3597;
UPDATE trabalho set email_corrigido='camila.rodriguescruz@upe.br ', titulo_corrigido='AVALIAÇÃO DA QUALIDADE EM UNIDADES BÁSICAS DE SAÚDE NO MUNICÍPIO DE SALGUEIRO: UMA APLICAÇÃO DO MODELO SERVQUAL' WHERE id=3547;
UPDATE trabalho set email_corrigido='andre.salvino@upe.br', titulo_corrigido='AVALIAÇÃO DA TOXICIDADE REPRODUTIVA DA GALACTOMANANA EXTRAÍDA DAS SEMENTES DE CASSIA GRANDIS EM RATAS  WISTAR' WHERE id=3546;
UPDATE trabalho set email_corrigido='aron.aquino@upe.br', titulo_corrigido='AVALIAÇÃO DO CONHECIMENTO DOS ESTUDANTES DE ESCOLAS PÚBLICAS DE SERRA TALHADA ACERCA DE GRAVIDEZ NA ADOLESCÊNCIA E PRÉ-NATAL' WHERE id=3609;
UPDATE trabalho set email_corrigido='hicky.cabral@gmail.com', titulo_corrigido='AVALIAÇÃO DO EFEITO DE REVESTIMENTOS DE POLISSACARÍDEOS NO TEMPO DE PRATELEIRA DE QUEIJOS PRODUZIDOS EM GARANHUNS' WHERE id=3827;
UPDATE trabalho set email_corrigido='daniel.medeirosnunes@upe.br', titulo_corrigido='AVALIAÇÃO DO EFEITO DO EXTRATO AQUOSO DAS FOLHAS DE MORINGA OLEIFERA EM DIFERENTES FASES DA GESTAÇÃO DE RATAS WISTAR' WHERE id=3567;
UPDATE trabalho set email_corrigido='hortencia.vitoria@upe.br', titulo_corrigido='AVALIAÇÃO DO EFEITO DO LASER DE BAIXA INTENSIDADE NAS CIRURGIAS EM TECIDO GENGIVAL ATRAVÉS DA PERCEPÇÃO DE DOR PÓS-OPERATÓRIA E QUALIDADE DE CICATRIZAÇÃO' WHERE id=3813;
UPDATE trabalho set email_corrigido='renata.farias@upe.br', titulo_corrigido='AVALIAÇÃO DO USO ABUSIVO DE ÁLCOOL EM ESTUDANTES UNIVERSITÁRIOS  ' WHERE id=3671;
UPDATE trabalho set email_corrigido='emille.herculano@upe.br', titulo_corrigido='AVALIAÇÃO DO USO DE TÉCNICAS DE CONTROLE DE COMPORTAMENTO EM ODONTOPEDIATRIA' WHERE id=3749;
UPDATE trabalho set email_corrigido='wesllayne.lima@upe.br', titulo_corrigido='BIBLIOTECA ITINERANTE: UMA LEITURA PARA A SAÚDE INFANTIL' WHERE id=3687;
UPDATE trabalho set email_corrigido='historia.veronica96@gmail.com', titulo_corrigido='BRINQUEDOTECA: O LABORATÓRIO DO PEDAGOGO E SUAS IMPLICAÇÕES SOCIOCULTURAIS' WHERE id=3634;
UPDATE trabalho set email_corrigido='karinerocha163@gmail.com', titulo_corrigido='CAMPANHA - A CIÊNCIA EM MINHA VIDA: RELATO DE EXPERIÊNCIA' WHERE id=3747;
UPDATE trabalho set email_corrigido='Isllany Karine Santos da Silva', titulo_corrigido='CÂNCER BUCAL: UM OLHAR A PARTIR DOS CASOS ENTRE OS POVOS INDÍGENAS ' WHERE id=3637;
UPDATE trabalho set email_corrigido='Henrique.bernardo@upe.br', titulo_corrigido='CANDOMBLÉ: UMA ANÁLISE SOCIOLÓGICA ' WHERE id=3596;
UPDATE trabalho set email_corrigido='breno.carvalho@gmail.com', titulo_corrigido='CARTOGRAFIA COM UMA BENZEDEIRA DO AGRESTE PERNAMBUCANO' WHERE id=3472;
UPDATE trabalho set email_corrigido='ruuth.brito@gmail.com', titulo_corrigido='CARTOGRAFIAS, ARTE E CRIAÇÃO NAS INFÂNCIAS' WHERE id=3499;
UPDATE trabalho set email_corrigido='launnovaes@upe.br', titulo_corrigido='CATADORES DE LIXO DAS REDONDEZAS DA UNIVERSIDADE DE PERNAMBUCO - CAMPUS GARANHUNS: OLHANDO PARA O INVISÍVEL' WHERE id=3700;
UPDATE trabalho set email_corrigido='joan.serafim@upe.br', titulo_corrigido='CEFALEIA TIPO TENSÃO E SEUS IMPACTOS NO RENDIMENTO ACADÊMICO E NAS ATIVIDADES COTIDIANAS DE ESTUDANTES UNIVERSITÁRIOS DE UM CURSO MÉDICO NO SERTÃO DE PERNAMBUCO' WHERE id=3510;
UPDATE trabalho set email_corrigido='lucas.henriquemonteiro@upe.br', titulo_corrigido='CHATTERBOT BASEADO EM MODELOS ONTOLÓGICOS PARA INFERIR CONSEQUÊNCIAS EM DIREITO PENAL' WHERE id=3560;
UPDATE trabalho set email_corrigido='thamires.mendes@upe.br', titulo_corrigido='COMPREENSÃO DE TEXTOS E SOCIEDADE: UM ESTUDO EXPLORATÓRIO ACERCA DE INDICATIVOS DE ABUSO SEXUAL INFANTIL NA COMPREENSÃO DE TEXTOS NARRATIVOS' WHERE id=3723;
UPDATE trabalho set email_corrigido='thiago.bezerraa@upe.br', titulo_corrigido='COMUNICADOR-A TELESSAÚDE COMO MODALIDADE DE EDUCAÇÃO EM DOR BASEADA EM NEUROCIÊNCIAS' WHERE id=3660;
UPDATE trabalho set email_corrigido='isabela.alima@upe.br', titulo_corrigido='CONDUTAS DE BIOSSEGURANÇA NA CONFECÇÃO DE PRÓTESES DENTÁRIAS EM UM CENÁRIO DE PANDEMIA' WHERE id=3605;
UPDATE trabalho set email_corrigido='silvia.camelo@upe.br', titulo_corrigido='CONECTA SAÚDE – RELATO DE EXPERIÊNCIA' WHERE id=3693;
UPDATE trabalho set email_corrigido='naninhacabral@gmail.com', titulo_corrigido='CONSIDERAÇÕES SOBRE O CONCEITO DE CIDADANIA À LUZ DA DECLARAÇÃO UNIVERSAL DA ONU DE 1948.' WHERE id=3590;
UPDATE trabalho set email_corrigido='isabelle.ferraz@upe.br', titulo_corrigido='CONSTRUÇÃO DA ESCALA DE INSÔNIA PARA MULHERES NA MENOPAUSA: UM RELATO DE EXPERIÊNCIA' WHERE id=3438;
UPDATE trabalho set email_corrigido='luedyna.leite@upe.br', titulo_corrigido='CONSTRUÇÃO DE UM LABORATÓRIO VIRTUAL DE HISTOPATOLOGIA ORAL COMO FERRAMENTA DE AUXÍLIO NO PROCESSO DE ENSINO-APRENDIZAGEM NO CURSO DE ODONTOLOGIA DA UPE CAMPUS ARCOVERDE' WHERE id=3577;
UPDATE trabalho set email_corrigido='juliana.henrique@upe.br', titulo_corrigido='CONSTRUÇÃO DO JOGO “RUMO A IMPLANTAÇÃO”: UM RELATO DE EXPERIÊNCIA' WHERE id=3464;
UPDATE trabalho set email_corrigido='bruno.smoura@upe.br', titulo_corrigido='CONTAÇÃO DA ARCA DE NOÉ EM CONTEXTO DE LETRAMENTO NA EDUCAÇÃO INFANTIL V' WHERE id=3620;
UPDATE trabalho set email_corrigido='silvanayharanara@hotmail.com', titulo_corrigido='CONTAÇÕES DE HISTÓRIAS: CONTRIBUIÇÕES E ESTRATÉGIAS NO CONTEXTO DA PANDEMIA DE COVID-19 EM UMA ESCOLA MUNICIPAL DE GARANHUNS. ' WHERE id=3494;
UPDATE trabalho set email_corrigido='iually.almeida@upe.br', titulo_corrigido='CONTRIBUIÇÕES DA MONITORIA ACADÊMICA DE DIDÁTICA NA PRÁTICA DOCENTE: RELAÇÃO ENTRE OS CURSOS DE LICENCIATURA EM MATEMÁTICA E COMPUTAÇÃO' WHERE id=3764;
UPDATE trabalho set email_corrigido='zenilda.silvestre@upe.br', titulo_corrigido='CONTRIBUIÇÕES DA PSICANÁLISE PARA A COMUNICAÇÃO E A DINÂMICA VINCULAR NA RELAÇÃO MÉDICO-PACIENTE: UMA REVISÃO DE LITERATURA' WHERE id=3444;
UPDATE trabalho set email_corrigido='natalia.bernardo@upe.br', titulo_corrigido='CONTRIBUIÇÕES DA TERAPIA COGNITIVO-COMPORTAMENTAL NA PSICOLOGIA DO ESPORTE: UMA REVISÃO DE LITERATURA' WHERE id=3728;
UPDATE trabalho set email_corrigido='joseeraimundoo@gmail.com', titulo_corrigido='CONTRIBUIÇÕES TEÓRICAS E EPISTÊMICAS DE BELL HOOKS À DISCUSSÃO SOBRE GÊNERO, MASCULINIDADE E RAÇA' WHERE id=3692;
UPDATE trabalho set email_corrigido='matheus-vieeira@hotmail.com', titulo_corrigido='CORONECTOMIA COMO TÉCNICA ALTERNATIVA A EXODONTIA: REVISÃO DE LITERATURA' WHERE id=3580;
UPDATE trabalho set email_corrigido='dryelledaianne@hotmail.com', titulo_corrigido='CORRELAÇÃO ENTRE CEFALEIA TIPO TENSÃO E  ATIVIDADES COTIDIANAS E ACADÊMICAS DE ESTUDANTES DE FISIOTERAPIA ' WHERE id=3600;
UPDATE trabalho set email_corrigido='eduarda.sobral@upe.br ', titulo_corrigido='CORRELAÇÃO ENTRE DEPRESSÃO, AMPLIFICAÇÃO DA DOR, RUMINAÇÃO, SENSAÇÃO DE DESAMPARO E RESTRIÇÃO NAS ATIVIDADES DIÁRIAS EM PORTADORES DE DOR CRÔNICA MUSCULOESQUELÉTICA' WHERE id=3536;
UPDATE trabalho set email_corrigido='mariaclaramnz93@gmail.com', titulo_corrigido='COSMÉTICOS ORGÂNICOS' WHERE id=3460;
UPDATE trabalho set email_corrigido='bruno.smartins@upe.br', titulo_corrigido='COTAS COMO MECANISMO DE REDUÇÃO DAS DESIGUALDADES SOCIAIS' WHERE id=3826;
UPDATE trabalho set email_corrigido='guilherme.vale@upe.br', titulo_corrigido='CRUZ E SOUSA E A DOR NEGRA DO EMPAREDADO: DESABAFOS E CRÍTICAS DE UM POETA AFRODESCENDENTE À UMA SOCIEDADE RACISTA E ESCRAVOCRATA' WHERE id=3497;
UPDATE trabalho set email_corrigido='nikesiaferreira@gmail.com', titulo_corrigido='CUIDADO DO CUIDADOR: O LUGAR DA PSICOLOGIA EM MEIO A PANDEMIA DE COVID-19' WHERE id=3571;
UPDATE trabalho set email_corrigido='olivia.amaral@upe.br', titulo_corrigido='CUIDADOS PALIATIVOS ONCOLÓGICOS NA ATENÇÃO PRIMÁRIA À SAÚDE NO BRASIL' WHERE id=3655;
UPDATE trabalho set email_corrigido='sergio.emmanuel@upe.br', titulo_corrigido='CULTURA DIGITAL NO ENSINO DE COMPUTAÇÃO COM O PIBID: CONTEXTUALIZAÇÃO E PRÁTICA SOBRE PHISHING E AMEAÇAS DIGITAIS NO IFPE' WHERE id=3757;
UPDATE trabalho set email_corrigido='matheus.souzaf@upe.br', titulo_corrigido='DANOS CUTÂNEOS DECORRENTES DA PROFILAXIA E DA BIOSSEGURANÇA CONTRA A COVID-19' WHERE id=3639;
UPDATE trabalho set email_corrigido='yasminsouzamourasouza@gmail.com', titulo_corrigido='DÉFICIT COGNITIVO CIRCUNSTANCIAL EM CRIANÇAS NO ÂMBITO ESCOLAR: UMA DISCUSSÃO NECESSÁRIA' WHERE id=3815;
UPDATE trabalho set email_corrigido='lurranesg@gmail.com', titulo_corrigido='DEIXA EU TE CONTAR UMA HISTÓRIA? UM RELATO DE EXPERIÊNCIA ACERCA DA ATUAÇÃO NO PIBID ' WHERE id=3498;
UPDATE trabalho set email_corrigido='igor.bulhoesbarros@upe.br', titulo_corrigido='DESAFIOS E PERSPECTIVAS DA RESIDÊNCIA PEDAGÓGICA EM GEOGRAFIA' WHERE id=3782;
UPDATE trabalho set email_corrigido='luma.andrade@upe.br', titulo_corrigido='DESAFIOS ENFRENTADOS PELOS PROFISSIONAIS DE SAÚDE QUANTO AOS CUIDADOS PALIATIVOS EM PACIENTES TERMINAIS ' WHERE id=3555;
UPDATE trabalho set email_corrigido='ninacarvalho1999@hotmail.com', titulo_corrigido='DESCONSTRUINDO GÊNERO, REVELANDO VIOLÊNCIAS: UMA INVESTIGAÇÃO ACERCA DAS PERFORMANCES FEMININAS DE GÊNERO EM DISPOSITIVOS LEGAIS BRASILEIROS' WHERE id=3488;
UPDATE trabalho set email_corrigido='mateus.carvalhog@upe.br', titulo_corrigido='DESFRAGMENTANDO O TRANSTORNO DISSOCIATIVO DE IDENTIDADE: UMA REVISÃO DA LITERATURA' WHERE id=3657;
UPDATE trabalho set email_corrigido='mariana.ricardo@upe.br', titulo_corrigido='DESMISTIFICANDO A SEXUALIDADE NA EDUCAÇÃO: COM FOCO NA PRIMEIRA INFÃNCIA' WHERE id=3787;
UPDATE trabalho set email_corrigido='wesleytsilva.ufpe@gmail.com', titulo_corrigido='DETECÇÃO DE STAPHYLOCOCCUS AUREUS RESISTENTE À METICILINA/OXACILINA EM EQUIPAMENTOS ATLÉTICOS DO PROGRAMA ACADEMIA RECIFE' WHERE id=3433;
UPDATE trabalho set email_corrigido='jleon9819@gmail.com', titulo_corrigido='DETERMINAÇÃO DO USO E COBERTURA DO SOLO NA MICRORREGIÃO DE GARANHUNS – PE, A PARTIR DO SENSORIAMENTO REMOTO' WHERE id=3647;
UPDATE trabalho set email_corrigido='flaviareginaf07@gmail.com', titulo_corrigido='DIMENSÕES E MEDIDA DE AVALIAÇÃO DA QUALIDADE DO SERVIÇO NO VAREJO: UMA PERSPECTIVA DE AUTOAVALIAÇÃO' WHERE id=3575;
UPDATE trabalho set email_corrigido='gabriel.eduardo@upe.br', titulo_corrigido='DINÂMICAS FAMILIARES E SAÚDE MENTAL DE JOVENS UNIVERSITÁRIOS NA PANDEMIA DE COVID-19' WHERE id=3441;
UPDATE trabalho set email_corrigido='kassandra.oliveira@upe.br', titulo_corrigido='DIRETRIZES CURRICULARES NACIONAIS PARA O ENSINO JURÍDICO E EDUCAÇÃO EM DIREITOS HUMANOS: APROXIMAÇÕES, TENSIONAMENTOS E PERSPECTIVAS ' WHERE id=3668;
UPDATE trabalho set email_corrigido='luciano.fabio@upe.br', titulo_corrigido='DISCIPLINA CURRICULAR DE EXTENSÃO “SAÚDE DO ADOLESCENTE”: RELATO DE EXPERIÊNCIA' WHERE id=3468;
UPDATE trabalho set email_corrigido='joaovitorgoncalves.mp@gmail.com', titulo_corrigido='DISFUNÇÕES TEMPOROMANDIBULARES E LASERTERAPIA DE BAIXA POTÊNCIA: UMA REVISÃO INTEGRATIVA' WHERE id=3672;
UPDATE trabalho set email_corrigido='araujots2000@gmail.com', titulo_corrigido='DITADURA MILITAR, MÍDIA E NARRATIVA HISTÓRICA NA CIDADE DE ARCOVERDE: UMA LEITURA A PARTIR DOS MEIOS DE COMUNICAÇÃO ' WHERE id=3531;
UPDATE trabalho set email_corrigido='gregoriodantas@hotmail.com', titulo_corrigido='DOENÇA DE GRAVES: ABORDAGENS CIRÚRGICAS E COMPLICAÇÕES' WHERE id=3717;
UPDATE trabalho set email_corrigido='gabriela.borges@upe.br', titulo_corrigido='DOR SENTIDA, DOR CALADA: (IN)VISIBILIDADES DO LUTO PERINATAL EM MULHERES QUILOMBOLAS' WHERE id=3452;
UPDATE trabalho set email_corrigido='laura.lima@upe.br', titulo_corrigido='EDUCA-AÇÃO: UMA FERRAMENTA DE TELESSAÚDE PARA PROFESSORES EM PERÍODO DE DISTANCIAMENTO SOCIAL ' WHERE id=3587;
UPDATE trabalho set email_corrigido='kauannazaidan69@gmail.com', titulo_corrigido='EDUCAÇÃO BILÍNGUE PARA SURDOS NOS ANOS INICIAIS DO ENSINO FUNDAMENTAL: ANÁLISE DA PRÁTICA EM UMA ESCOLA MUNICIPAL DE JUREMA-PE' WHERE id=3565;
UPDATE trabalho set email_corrigido='gabrielaalmeidarocha@hotmail.com', titulo_corrigido='EDUCAÇÃO COGNITIVA E DESENVOLVIMENTO HUMANO: DA INFÂNCIA AO ENVELHECIMENTO' WHERE id=3653;
UPDATE trabalho set email_corrigido='brenda.araujo@upe.br', titulo_corrigido='EDUCAÇÃO EM CONTEXTO PANDÊMICO:  A IMPORTÂNCIA DA MONITORIA ACADÊMICA' WHERE id=3722;
UPDATE trabalho set email_corrigido='kauanne.ribeiro@upe.br', titulo_corrigido='EDUCAÇÃO EM ONCOLOGIA: INFORMAR, PREVENIR E CUIDAR' WHERE id=3581;
UPDATE trabalho set email_corrigido='lucas.dantas@upe.br', titulo_corrigido='EDUCAÇÃO EM SAÚDE BUCAL COLETIVA: CRIATIVIDADE E  DISSEMINAÇÃO DO CONHECIMENTO' WHERE id=3799;
UPDATE trabalho set email_corrigido='lucas.couto@upe.br', titulo_corrigido='EDUCAÇÃO EM SAÚDE EM TEMPOS DE PANDEMIA: UM RELATO DE EXPERIÊNCIA' WHERE id=3514;
UPDATE trabalho set email_corrigido='biancabarroso000@gmail.com', titulo_corrigido='EDUCAÇÃO EM SAÚDE MENTAL NA SALA DE ESPERA NO CAPS I: RELATO DE EXPERIÊNCIA ACADÊMICO' WHERE id=3800;
UPDATE trabalho set email_corrigido='mariliassantana13@gmail.com', titulo_corrigido='EDUCAÇÃO EM SAÚDE SOBRE PARASITOSES INTESTINAIS EM ESCOLA MUNICIPAL DE SERRA TALHADA: UM RELATO DE EXPERIÊNCIA' WHERE id=3778;
UPDATE trabalho set email_corrigido='charles.vilela@upe.br', titulo_corrigido='EDUCAÇÃO MIDIÁTICA E CULTURA DIGITAL: EXPERIÊNCIAS E IMPACTOS DO PIBID EM INFORMÁTICA NA EREM CAETÉS-PE' WHERE id=3746;
UPDATE trabalho set email_corrigido='bruno.nascimentolacerda@upe.br', titulo_corrigido='EFEITO DO MISOPROSTOL EM GESTANTES: UMA REVISÃO DE LITERATURA' WHERE id=3478;
UPDATE trabalho set email_corrigido='gabriella.apolinarioxavier@upe.br', titulo_corrigido='EFEITOS DA LASERTERAPIA EM PACIENTES COM MUCOSITE ORAL EM TRATAMENTO RADIOTERÁPICO PARA O CÂNCER DE BOCA E OROFARINGE' WHERE id=3627;
UPDATE trabalho set email_corrigido='lurian.sthefani@upe.br', titulo_corrigido='EFEITOS DOS AGENTES DESSENSIBILIZANTES NA REDUÇÃO DA SENSIBILIDADE CAUSADA PELO CLAREAMENTO DENTAL' WHERE id=3814;
UPDATE trabalho set email_corrigido='daniel.medeirosnunes@upe.br', titulo_corrigido='EFEITOS TERATOGÊNICOS DO USO DA ISOTRETINOÍNA DURANTE A GESTAÇÃO – UMA REVISÃO DE LITERATURA' WHERE id=3608;
UPDATE trabalho set email_corrigido='luiz.eduardoleite@upe.br', titulo_corrigido='EFICÁCIA DAS MÁSCARAS N95/PFF-2 NA PROTEÇÃO CONTRA A COVID-19 EM ATENDIMENTOS ODONTOLÓGICOS COM AEROSSÓIS: UMA REVISÃO DA LITERATURA' WHERE id=3795;
UPDATE trabalho set email_corrigido='higor.monteiro@upe.br', titulo_corrigido='ENCONTROS CULTURAIS DE PERNAMBUCO EM TEMPOS DE PANDEMIA' WHERE id=3752;
UPDATE trabalho set email_corrigido='camillacynara0@gmail.com', titulo_corrigido='ENCONTROS E CONFRONTROS: DILEMAS ENTRE O MOVIMENTO LGBT E O ATIVISMO QUEER' WHERE id=3681;
UPDATE trabalho set email_corrigido='jvictor.souza@upe.br', titulo_corrigido='ENTRE A MEMÓRIA E O SILÊNCIO: UMA ÓTICA DA INSTRUMENTALIZAÇÃO RETÓRICA DA NARRATIVA NA POLÍTICA' WHERE id=3817;
UPDATE trabalho set email_corrigido='eduarda.nascimento@upe.br', titulo_corrigido='ENTRELACE ENTRE SAÚDE E CUIDADO COM A TERRA EM COMUNIDADE QUILOMBOLA: NARRATIVAS DA JUVENTUDE.' WHERE id=3699;
UPDATE trabalho set email_corrigido='mnathalia.napoleao@gmail.com', titulo_corrigido='ENTRELACE ENTRE SAÚDE E O CUIDADO COM A TERRA EM COMUNIDADE QUILOMBOLA: NARRATIVA DE IDOSOS' WHERE id=3648;
UPDATE trabalho set email_corrigido='halainecristinapessoa@gmail.com', titulo_corrigido='ENTREVISTAS COM JOVENS RORAIMENSES SOBRE O SENTIDO DA MATERNIDADE NA ADOLESCÊNCIA' WHERE id=3777;
UPDATE trabalho set email_corrigido='kilder.leon@upe.br', titulo_corrigido='EQUIPES MULTIPROFISSIONAIS: SAÚDE MENTAL LABORAL E FATORES MOTIVACIONAIS' WHERE id=3564;
UPDATE trabalho set email_corrigido='ludmilla.souza@upe.br', titulo_corrigido='ESCRITA CIENTÍFICA NA GRADUAÇÃO: DIFICULDADES E VIVÊNCIAS DOS ESTUDANTES DE ODONTOLOGIA EM PERNAMBUCO' WHERE id=3640;
UPDATE trabalho set email_corrigido='mirelysantiago@upe.br', titulo_corrigido='ESCRITÓRIO DE DEFESA DA MULHER: DA VIOLÊNCIA PSICOLÓGICA AO DANO EMOCIONAL' WHERE id=3740;
UPDATE trabalho set email_corrigido='bruna.lucas@upe.br', titulo_corrigido='ESCRITÓRIO DE DEFESA DA MULHER: RADICALIDADE E FORMAÇÃO CRÍTICA' WHERE id=3762;
UPDATE trabalho set email_corrigido='joao.victordomingos@upe.br', titulo_corrigido='ESTÁGIO EM PSICOLOGIA CLÍNICA NUMA PANDEMIA: A PSICOTERAPIA DE GRUPO NO CONTEXTO REMOTO' WHERE id=3730;
UPDATE trabalho set email_corrigido='lucianatteodosio@gmail.com', titulo_corrigido='ESTÁGIOS REMOTOS NO CURSO DE LICENCIATURA EM LETRAS: RELATO DE EXPERIÊNCIA' WHERE id=3793;
UPDATE trabalho set email_corrigido='laynara.motamalta@upe.br', titulo_corrigido='ETIOLOGIA E TRATAMENTO DO INSUCESSO ENDODÔNTICO: REVISÃO DE LITERATURA' WHERE id=3794;
UPDATE trabalho set email_corrigido='deyvisson.luis@upe.br', titulo_corrigido='EXERCÍCIOS FÍSICOS COMO UM IMPORTANTE PROMOTOR DE SAÚDE: UMA REVISÃO DE LITERATURA' WHERE id=3484;
UPDATE trabalho set email_corrigido='baltebezerra@gmail.com', titulo_corrigido='EXODONTIAS E OSTEOTOMIA PARA RECUPERAÇÃO DE ESPAÇO E REABILITAÇÃO PROTÉTICO: RELATO DE CASO' WHERE id=3649;
UPDATE trabalho set email_corrigido='marcianacarvalho747@gmail.com', titulo_corrigido='EXPERIÊNCIAS VIVENCIADAS NO PIBID DE PEDAGOGIA DA  UFAPE: ACOMPANHAMENTO DE TURMAS DO 2º ANO DOS  ANOS INICIAIS DO ENSINO FUNDAMENTAL DE UMA ESCOLA  MUNICIPAL DE GARANHUNS NO CONTEXTO DA PANDEMIA  DE COVID-19 ' WHERE id=3502;
UPDATE trabalho set email_corrigido='daniel.bsales@upe.br', titulo_corrigido='EXPLORANDO A SRAG ATRAVÉS DE ESTRATÉGIAS DE APRENDIZAGEM DE MÁQUINA: UMA ABORDAGEM BASEADA NA PNAD COVID 19' WHERE id=3798;
UPDATE trabalho set email_corrigido='gabrielli.vieira@upe.br', titulo_corrigido='EXTRAÇÃO E CARACTERIZAÇÃO FÍSICO-QUÍMICA DE POLISSACARÍDEOS ORIUNDOS DO AGRESTE DE PERNAMBUCO PARA PRODUÇÃO DE HIDROGÉIS COM POTENCIAL APLICAÇÃO BIOTECNOLÓGICA' WHERE id=3578;
UPDATE trabalho set email_corrigido='pollyrodrigues386@gmail.com', titulo_corrigido='FAKE NEWS E ALGORITMOS: UMA VISÃO ARENDTIANA SOBRE VERDADE E MENTIRA NA POLÍTICA E SEUS REFLEXOS EM ESTRUTURAS DIGITAIS DE CONTROLE' WHERE id=3537;
UPDATE trabalho set email_corrigido='b-boy-uzumaki@hotmail.com', titulo_corrigido='FERRAMENTAS DE ANÁLISE ESPACIAIS COMO SUBSÍDIO A TOMADA DE DECISÃO NO DESENVOLVIMENTO SOCIOAMBIENTAL' WHERE id=3582;
UPDATE trabalho set email_corrigido='mariaelioneyde.silva@upe.br', titulo_corrigido='FESTA DE SÃO FRANCISCO DE ASSIS: FÉ E DEVOÇÃO NO MUNICÍPIO DE IBIRAJUBA - PE' WHERE id=3694;
UPDATE trabalho set email_corrigido='gabriela.borges@upe.br', titulo_corrigido='FLORES-CER CUIDADO' WHERE id=3770;
UPDATE trabalho set email_corrigido='felipe.joc@hotmail.com', titulo_corrigido='FORTALECENDO O ENSINO DA BIOQUÍMICA COM NOVAS ESTRATÉGIAS: UM RELATO DE CASO SOBRE O USO DE METODOLOGIAS ATIVAS NO CURSO DE MEDICINA DA UPE GARANHUNS' WHERE id=3756;
UPDATE trabalho set email_corrigido='yasmin.britto@upe.br', titulo_corrigido='FREQUÊNCIA DE ACIDENTES E COMPLICAÇÕES NOS PROCEDIMENTOS DE CIRURGIA BUCO-DENTAL EXECUTADOS NA CLÍNICA DO BACHARELADO EM ODONTOLOGIA DA UNIVERSIDADE DE PERNAMBUCO, CAMPUS ARCOVERDE' WHERE id=3665;
UPDATE trabalho set email_corrigido='joicy.mirelly@upe.br', titulo_corrigido='GAMIFICAÇÃO NO CICLO DE ALFABETIZAÇÃO: UMA ESTRATÉGIA PARA POTENCIAIZAR O DESENVOLVIMENTO DA CONSCIÊNCIA FONOLÓGICA' WHERE id=3772;
UPDATE trabalho set email_corrigido='daniel.bsales@upe.br', titulo_corrigido='GAMIFICAÇÃO NO ENSINO DE L1 E L2 PARA SURDOS: UMA PROPOSTA DE FERRAMENTA COMPUTACIONAL' WHERE id=3445;
UPDATE trabalho set email_corrigido='flavia.ribeirofg@gmail.com', titulo_corrigido='GÊNERO E RAÇA NO ENSINO DE HISTÓRIA: CONTRIBUIÇÕES DO PENSAMENTO DECOLONIAL.' WHERE id=3666;
UPDATE trabalho set email_corrigido='deyvid.luam@upe.br', titulo_corrigido='GEOTURISMO COMO POSSIBILIDADE PARA COMPREENSÃO DA NATUREZA ABIÓTICA' WHERE id=3492;
UPDATE trabalho set email_corrigido='isaene.santos@upe.br', titulo_corrigido='GLOBALIZAÇÃO E SOBERANIA NA ORDEM JURÍDICA INTERNACIONAL' WHERE id=3726;
UPDATE trabalho set email_corrigido='naraanadao@gmail.com', titulo_corrigido='GRUPO TERAPÊUTICO REMOTO E A POSSIBILIDADE DE ACOLHIMENTO AO LUTO PERINATAL: UM RELATO DE EXPERIÊNCIAS' WHERE id=3825;
UPDATE trabalho set email_corrigido='zenilda.silvestre@upe.br', titulo_corrigido='HANSENÍASE: UMA DOENÇA NEGLIGENCIADA NO NORDESTRE BRASILEIRO' WHERE id=3482;
UPDATE trabalho set email_corrigido='marcos.moises@upe.br', titulo_corrigido='HISTÓRIA LOCAL, USO DE FONTES ORAIS E CONTEÚDO PROGRAMÁTICO: CONTRAPONTOS E POSSIBILIDADES' WHERE id=3506;
UPDATE trabalho set email_corrigido='alessandratorres2005@gmail.com', titulo_corrigido='IDENTIFICAÇÃO BOTÂNICA E USO MEDICINAL DE ESPÉCIES DO AGRESTE MERIDICIONAL PERNAMBUCANO' WHERE id=3741;
UPDATE trabalho set email_corrigido='aline.cordeiro@upe.br', titulo_corrigido='IDENTIFICANDO O NÍVEL DE CONHECIMENTO DA POPULAÇÃO DE CACHOEIRINHA-PE EM RELAÇÃO AO PLANO MUNICIPAL DE EDUCAÇÃO DO MUNICÍPIO ' WHERE id=3572;
UPDATE trabalho set email_corrigido='alisson.rodrigo@upe.br', titulo_corrigido='IDENTIFICANDO XENOFOBIA EM POSTAGENS DO TWITTER USANDO SUPPORT VECTOR MACHINE COM A ESTRATÉGIA TF/IDF' WHERE id=3585;
UPDATE trabalho set email_corrigido='eryka.sobral@upe.br', titulo_corrigido='II SEMINÁRIO DE ESTÁGIO E EMPREGABILIDADE DE SALGUEIRO: PROJETO DE EXTENSÃO ONLINE' WHERE id=3824;
UPDATE trabalho set email_corrigido='leandrotiago555@gmail.com', titulo_corrigido='IMAGINÁRIO E CANDOMBLÉ JEJE DO TERREIRO T''AZIRY LADÊ: DIMENSÕES SIMBÓLICAS, GESTUALIDADES E ESTÉTICAS' WHERE id=3676;
UPDATE trabalho set email_corrigido='alvaro_henrique001@hotmail.com', titulo_corrigido='IMAGIOLOGIA NA ODONTOLOGIA: BIDIMENSIONALIDADE VERSUS TRIDIMENSIONALIDADE' WHERE id=3447;
UPDATE trabalho set email_corrigido='joice.catiane@upe.br', titulo_corrigido='IMPACTO DE MÉTODOS DE POLIMENTO DE COMPÓSITOS NA ADESÃO, PROLIFERAÇÃO E PATOGENICIDADE DE MICROORGANISMOS BUCAIS: UMA REVISÃO DA LITERATURA' WHERE id=3603;
UPDATE trabalho set email_corrigido='jordana.gabriela@upe.br', titulo_corrigido='IMPACTOS DA COEXISTÊNCIA DA PANDEMIA DO COVID-19 E EPIDEMIAS DE DENGUE NO BRASIL: UMA REVISÃO DE LITERATURA' WHERE id=3613;
UPDATE trabalho set email_corrigido='crisbleite1611@gmail.com', titulo_corrigido='IMPACTOS DA FORMAÇÃO EM LUTO PERINATAL PARA ESTUDANTES E PROFISSIONAIS DE SAÚDE: UM RELATO DE EXPERIÊNCIAS' WHERE id=3465;
UPDATE trabalho set email_corrigido='wanderson.rafael@upe.br', titulo_corrigido='IMPACTOS DA PANDEMIA DO COVID-19 NA ASSISTÊNCIA PRIMÁRIA AO PÚBLICO FEMININO – UMA REVISÃO DE LITERATURA' WHERE id=3674;
UPDATE trabalho set email_corrigido='jfernando.reis@upe.br', titulo_corrigido='IMPERIALISMO E IDEOLOGIA: UM PASSEIO PELA DEFINIÇÃO DO PENSADOR LOUIS ALTHUSSER' WHERE id=3734;
UPDATE trabalho set email_corrigido='andrea.amaral@upe.br', titulo_corrigido='IMPLANTAÇÃO E FUNCIONAMENTO DA CÂMARA PRIVADA DE CONCILIAÇÃO E MEDIAÇÃO – CPCM – UPE / ARCOVERDE' WHERE id=3776;
UPDATE trabalho set email_corrigido='everton11menezes@gmail.com', titulo_corrigido='IMPLANTES DENTÁRIOS EM PACIENTES ONCOLÓGICOS: UMA REVISÃO' WHERE id=3711;
UPDATE trabalho set email_corrigido='vicctoriana22@gmail.com', titulo_corrigido='IMPORTÂNCIA DA COMPREENSÃO SOBRE O DESENVOLVIMENTO HUMANO PARA APRENDIZAGEM/FORMAÇÃO ACADÊMICA' WHERE id=3632;
UPDATE trabalho set email_corrigido='andre.falabella@upe.br', titulo_corrigido='INFLUÊNCIA DO DIREITO NO RACISMO: UMA QUESTÃO SÓCIO-HISTÓRICA' WHERE id=3754;
UPDATE trabalho set email_corrigido='raphaelamarrise@gmail.com', titulo_corrigido='INFLUÊNCIAS DO ROCOCÓ E DA ART NOUVEAU NAS EMBALAGENS COLECIONÁVEIS DA MARIE ANGE DI COSTA.' WHERE id=3643;
UPDATE trabalho set email_corrigido='thayspereira251@gmail.com', titulo_corrigido='INICIAÇÃO CIENTÍFICA NA GRADUAÇÃO: UMA EXPERIÊNCIA TRANSFORMADORA' WHERE id=3476;
UPDATE trabalho set email_corrigido='patriciaingridp@gmail.com', titulo_corrigido='INSTALAÇÃO IMEDIATA DE IMPLANTES APÓS EXODONTIAS: POSSIBILIDADES E LIMITAÇÕES PARA OSSEOINTEGRAÇÃO' WHERE id=3646;
UPDATE trabalho set email_corrigido='alanny.magalhaes@hotmail.com', titulo_corrigido='INTERAÇÃO SOCIAL NO AMBIENTE ESCOLAR: A IMPORT NCIA DESTA PARA A APRENDIZAGEM INFANTIL DIANTE DE UM CONTEXTO PANDÊMICO' WHERE id=3768;
UPDATE trabalho set email_corrigido='valdenilson.silva@upe.br', titulo_corrigido='JOVEM GUARDA - UMA= OLHAR SOBRE A HISTÓRIA' WHERE id=3467;
UPDATE trabalho set email_corrigido='gabriel.eduardo@upe.br', titulo_corrigido='JUVENTUDE BRASILEIRA E A TRANSIÇÃO PARA A VIDA ADULTA: UMA REVISÃO SISTEMÁTICA' WHERE id=3442;
UPDATE trabalho set email_corrigido='paula.siqueira@upe.br', titulo_corrigido='JUVENTUDE E POBREZA NO BRASIL: UMA BREVE REVISÃO BIBLIOGRÁFICA' WHERE id=3611;
UPDATE trabalho set email_corrigido='felipe.joc@hotmail.com', titulo_corrigido='LEVANTAMENTO DE ESPÉCIES DE LENTILHAS EM RESERVATÓRIOS DE BOM CONSELHO-PE' WHERE id=3528;
UPDATE trabalho set email_corrigido='joaopaulobiologia4@gmail.com', titulo_corrigido='LEVANTAMENTO, CARACTERIZAÇÃO, MAPEAMENTO E INVENTARIAÇÃO DE GEOFORMAS / GEOMORFOSSITIOS DO PARQUE MUNICIPAL DA PEDRA FURADA, VENTUROSA, PERNAMBUCO.' WHERE id=3529;
UPDATE trabalho set email_corrigido='taliny.barros@upe.br', titulo_corrigido='LITERATURA AFRICANA E ENSINO DE HISTORIA: POSSIVEIS CAMINHOS EM SALA DE AULA' WHERE id=3710;
UPDATE trabalho set email_corrigido='laricecabral48@gmail.com', titulo_corrigido='LUTO NEONATAL NA PANDEMIA DA COVID-19: COMO OS PAIS LIDAM?' WHERE id=3594;
UPDATE trabalho set email_corrigido='basiliogleyce@hotmail.com', titulo_corrigido='LYNXACARUS RADOVSKYI EM GATO DOMÉSTICO: RELATO DE CASO' WHERE id=3802;
UPDATE trabalho set email_corrigido='kcrystini@gmail.com', titulo_corrigido='MANEJO DA ASMA NA INFÂNCIA: ATUALIZAÇÃO SEGUNDO O GINA 2019 E A SOCIEDADE BRASILEIRA DE PNEUMOLOGIA E TISIOLOGIA 2020' WHERE id=3629;
UPDATE trabalho set email_corrigido='guilherme.vale@upe.br', titulo_corrigido='MANIFESTOS, PANFLETOS E  MIMEÓGRAFOS A(R)MADOS: A CONTRACULTURA MANIFESTADA NA POESIA MARGINAL DOS ANOS 70 NO BRASIL' WHERE id=3820;
UPDATE trabalho set email_corrigido='francisca_cipriano@hotmail.com', titulo_corrigido='MAPEANDO SUBJETIVIDADES FEMININAS QUILOMBOLAS: CONSIDERAÇÕES CRÍTICAS DIANTE DE CAMPOS SINGULARES' WHERE id=3697;
UPDATE trabalho set email_corrigido='gabrielaalmeidarocha@hotmail.com', titulo_corrigido='METACOGNIÇÃO DE FUNÇÕES EXECUTIVAS JUNTO A UMA CRIANÇA DE 8 ANOS: ESTUDO DE CASO' WHERE id=3684;
UPDATE trabalho set email_corrigido='daniel.candido@upe.br', titulo_corrigido='METODOLOGIAS ATIVAS PARA O PROCESSO DE ENSINO-APRENDIZAGEM DAS DISCIPLINAS DE MATEMÁTICA BÁSICA I E MATEMÁTICA BÁSICA II' WHERE id=3449;
UPDATE trabalho set email_corrigido='milenaalmeidaveloso@gmail.com', titulo_corrigido='MONITORIA ACADÊMICA EM DIREITO PROCESSUAL PENAL: UM OLHAR CRÍTICO NECESSÁRIO' WHERE id=3789;
UPDATE trabalho set email_corrigido='karinerocha163@gmail.com', titulo_corrigido='MONITORIA COMO FERRAMENTA AUXILIAR NO ENSINO DA DISCIPLINA DE TÉCNICA CIRÚRGICA VETERINÁRIA DURANTE AS AULAS REMOTAS' WHERE id=3691;
UPDATE trabalho set email_corrigido='arianny.brandao@upe.br', titulo_corrigido='MONITORIA DA DISCIPLINA DE ATENÇÃO SECUNDÁRIA EM SAÚDE BUCAL I: UM RELATO DE EXPERIÊNCIA' WHERE id=3686;
UPDATE trabalho set email_corrigido='angelica.santos@aluno.uepb.edu.br', titulo_corrigido='MONITORIA DE ESTUDOS E ATIVIDADES PRÁTICAS EM MICROBIOLOGIA E PARASITOLOGIA: UMA FORMA DINÂMICA DE APRENDIZADO E CAPACITAÇÃO ACADÊMICA' WHERE id=3512;
UPDATE trabalho set email_corrigido='milene.duarte@upe.br', titulo_corrigido='MONITORIA DE PATOLOGIA ALTERAÇÕES MORFOLÓGICAS E MOLECULARES GERAIS DAS DOENÇAS: RELATO DE EXPERIÊNCIA' WHERE id=3682;
UPDATE trabalho set email_corrigido='arthurmeloprof@gmail.com', titulo_corrigido='MONITORIA DURANTE O PERÍODO LETIVO EXCEPCIONAL: RELATOS DE ENSINO E APRENDIZAGEM NA DISCIPLINA DE GÊNEROS ACADÊMICOS E METODOLOGIA CIENTÍFICA' WHERE id=3792;
UPDATE trabalho set email_corrigido='sarahcavalcantedasilva@gmail.com', titulo_corrigido='MONITORIA NA FORMAÇÃO INICIAL: REFLEXÕES DO LUGAR, ESPAÇO E TEMPO DAS EXPERIÊNCIAS FORMATIVAS' WHERE id=3707;
UPDATE trabalho set email_corrigido='giselemendes1997@gmail.com', titulo_corrigido='MONITORIA NO CONTEXTO DE COMO SER PROFESSOR: UM DESVELAR CRÍTICO DA EXPERIÊNCIA E DA FORMAÇÃO' WHERE id=3715;
UPDATE trabalho set email_corrigido='matheus.madeira10@gmail.com', titulo_corrigido='MONITORIA PARA O DESENVOLVIMENTO DE ESTRATÉGIAS FACILITADORAS DA APRENDIZAGEM DO MÓDULO DE PRÁTICA MÉDICA VI: UM RELATO DE EXPERIÊNCIA' WHERE id=3743;
UPDATE trabalho set email_corrigido='vitoriapaesg@gmail.com', titulo_corrigido='MUDARAM AS ESTAÇÕES: A ELABORAÇÃO DO LUTO NA ADOLESCÊNCIA' WHERE id=3598;
UPDATE trabalho set email_corrigido='eduarda.josianebraga@upe.br', titulo_corrigido='MÚSICA DE PROTESTO E ENSINO DE HISTÓRIA: UM RELATO DE EXPERIÊNCIA ' WHERE id=3570;
UPDATE trabalho set email_corrigido='gabriel.cruz@upe.br', titulo_corrigido='MÚSICA INDÍGENA E COLONIAL' WHERE id=3471;
UPDATE trabalho set email_corrigido='alan.costa@upe.br', titulo_corrigido='MUTAÇÕES E CARACTERÍSTICAS DA VARIANTE BRASILEIRA DO SARS-COV-2: UMA REVISÃO DE LITERATURA' WHERE id=3558;
UPDATE trabalho set email_corrigido='emanuelly.brito@upe.br', titulo_corrigido='NÍVEL DE CONHECIMENTO DOS CIRURGIÕES-DENTISTAS ACERCA DOS TRAUMATISMOS DENTÁRIOS: UMA REVISÃO DA LITERATURA' WHERE id=3736;
UPDATE trabalho set email_corrigido='b-boy-uzumaki@hotmail.com', titulo_corrigido='NÓS PROPOMOS A UTILIZAÇÃO DE JOGOS ELETRÔNICOS COMO FERRAMENTA DIDÁTICA PARA O ENSINO DE GEOGRAFIA' WHERE id=3737;
UPDATE trabalho set email_corrigido='TONTOM1978@HOTMAIL.COM', titulo_corrigido='NOVO CAMINHO PARA O ENSINO DE HISTÓRIA A PARTIR DA MEMÓRIA E IDENTIDADE' WHERE id=3443;
UPDATE trabalho set email_corrigido='kilder.leon@upe.br', titulo_corrigido='NUCAS EM REDE III: DIFERENTES ENCONTROS, SABERES E AFETOS EM TEMPOS DE PANDEMIA' WHERE id=3703;
UPDATE trabalho set email_corrigido='allanafreires2000@gmail.com', titulo_corrigido='O  INCREMENTO DE CARBOIDRATOS NA DIETA APRIMORA OS LIMITES FISIOLÓGICOS TÉRMICOS DE FORMIGAS DIURNAS E NOTURNAS' WHERE id=3489;
UPDATE trabalho set email_corrigido='elson.junior.015@gmail.com', titulo_corrigido='O CÂNCER DE COLO DE ÚTERO NO BRASIL: UMA REVISÃO DAS PRINCIPAIS ESTRATÉGIAS DE MONITORAMENTO' WHERE id=3625;
UPDATE trabalho set email_corrigido='lidienesilva90@gmail.com', titulo_corrigido='O CONHECIMENTO ALÉM DOS MUROS ESCOLARES' WHERE id=3435;
UPDATE trabalho set email_corrigido='kaliandra.guedes@upe.br', titulo_corrigido='O CUIDADO À GESTANTE NO SERVIÇO PRIMÁRIO: ATENÇÃO PERINATAL EM TEMPOS DE COVID-19' WHERE id=3732;
UPDATE trabalho set email_corrigido='siatmelo@gmail.com', titulo_corrigido='O CURRÍCULO NA PERSPECTIVA DO SABER “VOLUME” – DIFERENÇAS ENTRE DOCUMENTOS CURRICULARES NACIONAIS EM RELAÇÃO AOS ANOS FINAIS DO ENSINO FUNDAMENTAL.' WHERE id=3739;
UPDATE trabalho set email_corrigido='coutoroseilda@gmail.com', titulo_corrigido='O DESCARTE CORRETO DOS RESÍDUOS SÓLIDOS NO MUNICÍPIO DE SURUBIM/PE, INÍCIO, DESAFIO E PERSPECTIVAS' WHERE id=3504;
UPDATE trabalho set email_corrigido='historia.veronica96@gmail.com', titulo_corrigido='O DIREITO À EDUCAÇÃO DE CRIANÇAS RESIDENTES EM UNIDADE DE ACOLHIMENTO: RELATO DE UMA EXPERIÊNCIA PEDAGÓGICA' WHERE id=3663;
UPDATE trabalho set email_corrigido='ingridjvieira@gmail.com', titulo_corrigido='O DIREITO AO CUIDADO DA SAÚDE MENTAL EM TEMPOS DA PANDEMIA DA COVID-19: ACOLHIMENTO ONLINE' WHERE id=3561;
UPDATE trabalho set email_corrigido='launnovaes@gmail.com', titulo_corrigido='O DIREITO AO CUIDADO EM SAÚDE MENTAL EM TEMPOS DE PANDEMIA DO COVID-19: AÇÕES DO CURSO DE PSICOLOGIA DA UPE' WHERE id=3690;
UPDATE trabalho set email_corrigido='carlos.henriqueanjos@upe.br', titulo_corrigido='O DIREITO PENAL COMO FORMA DE CONTROLE SOCIAL: CAUSAS E CONSEQUÊNCIAS SOB A PERSPECTIVA SOCIOLÓGICA' WHERE id=3500;
UPDATE trabalho set email_corrigido='tainnah.leite@upe.br', titulo_corrigido='O EFEITO TERAPÊUTICO DA FOTOTERAPIA NA ICTERÍCIA NEONATAL: UMA REVISÃO DE LITERATURA ' WHERE id=3485;
UPDATE trabalho set email_corrigido='shirleyalves13@outlook.com', titulo_corrigido='O EMPODERAMENTO DA ENFERMAGEM NAS AÇÕES DE PREVENÇÃO A COVID-19' WHERE id=3486;
UPDATE trabalho set email_corrigido='annacarolinabio23@gmail.com', titulo_corrigido='O GÊNERO ABSIDIA E SUAS APLICAÇÕES BIOTECNOLÓGICAS' WHERE id=3607;
UPDATE trabalho set email_corrigido='hidelbrandolino@gmail.com', titulo_corrigido='O IMAGINÁRIO DA FEIRA LIVRE' WHERE id=3702;
UPDATE trabalho set email_corrigido='gustavoazsouza@gmail.com', titulo_corrigido='O IMPACTO DA PANDEMIA DO COVID-19 NA AUTONOMIA FUNCIONAL EM IDOSOS' WHERE id=3592;
UPDATE trabalho set email_corrigido='jorge.mendes@upe.br', titulo_corrigido='O IMPACTO DE INTERVENÇÕES COM RPG NA APRENDIZAGEM DE JOVENS E ADOLESCENTES' WHERE id=3766;
UPDATE trabalho set email_corrigido='fernanda.sacarvalho@upe.br', titulo_corrigido='O LÚDICO NA ODONTOPEDIATRIA: LIDANDO COM O MEDO E A ANSIEDADE' WHERE id=3735;
UPDATE trabalho set email_corrigido='gabriellaf495@gmail.com', titulo_corrigido='O LUGAR DAS TECNOLOGIAS NO ENSINO DE GEOGRAFIA: OLHARES A PARTIR DO PRGRAMA RESIDÊNCIA PEDAGÓGICA EM TEMPOS DE PANDEMIA – APONTAMENTOS INICIAIS' WHERE id=3801;
UPDATE trabalho set email_corrigido='glenda.sabia@upe.br', titulo_corrigido='O LUGAR DOS SUJEITOS LGBTQIA+ FRENTE À POLÍTICA BRASILEIRA' WHERE id=3533;
UPDATE trabalho set email_corrigido='nathalia.lazaroto@upe.br', titulo_corrigido='O PAPEL DA ATENÇÃO PRIMÁRIA À SAÚDE NA PANDEMIA DO COVID 19 NO BRASIL' WHERE id=3645;
UPDATE trabalho set email_corrigido='denisemoura818@gmail.com', titulo_corrigido='O PAPEL DO CIRURGIÃO DENTISTA NO ATENDIMENTO À MULHERES VÍTIMAS DE VIOLÊNCIA DOMÉSTICA' WHERE id=3554;
UPDATE trabalho set email_corrigido='emilly.aiany@upe.br', titulo_corrigido='O PERIGO DE UMA HISTÓRIA ÚNICA ASSOCIADA À VIOLÊNCIA CONJUGAL LÉSBICA' WHERE id=3701;
UPDATE trabalho set email_corrigido='enfgleison@icloud.com', titulo_corrigido='O POTENCIAL BIOTECNOLÓGICO DE FUNGOS FILAMENTOSOS NA SÍNTESE VERDE DE NANOPARTÍCULAS DE PRATA: UMA BREVE REVISÃO' WHERE id=3614;
UPDATE trabalho set email_corrigido='alexander.philippi@upe.br', titulo_corrigido='O QUE DIZEM OS NÚMEROS: UM RELATO DE EXPERIÊNCIA A PARTIR DA MONITORIA UNIVERSITÁRIA EM PSICOLOGIA E ESTATÍSTICA' WHERE id=3780;
UPDATE trabalho set email_corrigido='alexaureliano968@gmail.com', titulo_corrigido='O SOFTWARE GOOGLE EARTH PRO COMO FERRAMENTA NAS AULAS REMOTAS DE GEOGRAFIA: APONTAMENTOS INICIAIS A PARTIR DA PRÁTICA DO PROGRAMA RESIDÊNCIA PEDAGÓGICA' WHERE id=3767;
UPDATE trabalho set email_corrigido='marcianocarvalho148@gmail.com', titulo_corrigido='O TEXTO NA SALA DE AULA NA PERSPECTIVA DO PROFESSOR DE LÍNGUA PORTUGUESA' WHERE id=3479;
UPDATE trabalho set email_corrigido='kacia.guedes@upe.br', titulo_corrigido='O UNIVERSO DOS MARGINALIZADOS NA PEÇA BLUE JEANS' WHERE id=3540;
UPDATE trabalho set email_corrigido='wesllensanguineto@hotmail.com', titulo_corrigido='O USO ALTERNATIVO DOS CANABINÓIDES COM FINS TERAPÊUTICOS PARA OS CASOS EXTREMOS' WHERE id=3659;
UPDATE trabalho set email_corrigido='camille.dutra@upe.br', titulo_corrigido='O USO DE CANNABIS NA ANALGESIA DA DOR ONCOLÓGICA' WHERE id=3658;
UPDATE trabalho set email_corrigido='isadora.alves@upe.br ', titulo_corrigido='O USO DE POLÍTICAS DE CRÉDITO NA AGRICULTURA FAMILIAR: UMA ANÁLISE DO PERFIL DE PRODUTORES NA MICRORREGIÃO DE SALGUEIRO' WHERE id=3678;
UPDATE trabalho set email_corrigido='samarasantana2211@gmail.com', titulo_corrigido='O USO DO EXERCÍCIO FÍSICO EM PESSOA COM AGRAVAMENTO DA DIABETES MELLITUS: NEUROPATIA DIABÉTICA' WHERE id=3544;
UPDATE trabalho set email_corrigido='lucasassis3333@gmail.com', titulo_corrigido='O USO DO EXERGAMES COMO FERRAMENTA PEDAGÓGICA PARA A INCLUSÃO DE ALUNOS COM DEFICIÊNCIA NAS AULAS DE EDUCAÇÃO FÍSICA' WHERE id=3541;
UPDATE trabalho set email_corrigido='joice.catiane@upe.br', titulo_corrigido='O USO DO HIDRÓXIDO DE CÁLCIO COMO FORRADOR: UMA REVISÃO SISTEMATIZADA' WHERE id=3612;
UPDATE trabalho set email_corrigido='joao.ipiranga@upe.br', titulo_corrigido='OBESIDADE INFANTIL E DISTÚRBIOS DO SONO: UMA REVISÃO INTEGRATIVA.' WHERE id=3543;
UPDATE trabalho set email_corrigido='mariana.silva2@upe.br', titulo_corrigido='ONSCIÊNCIA HISTÓRICA EM TEMPOS PANDÊMICOS (COVID-19): A UTILIZAÇÃO DE FONTES E NOVAS PLATAFORMAS NO ENSINO DE HISTÓRIA' WHERE id=3696;
UPDATE trabalho set email_corrigido='alexgonsalvess1@gmail.com', titulo_corrigido='OS DESAFIOS DA EDUCAÇÃO QUILOMBOLA NO BRASIL' WHERE id=3562;
UPDATE trabalho set email_corrigido='lilian.souza@upe.br', titulo_corrigido='OS DESAFIOS NO PROCESSO DE ENSINO E APRENDIZAGEM NAS AULAS ON-LINE DE MATEMÁTICA ' WHERE id=3519;
UPDATE trabalho set email_corrigido='danielesbernardo23@gmail.com', titulo_corrigido='OS DILEMAS DA FRONTEIRA E IDENTIDADE ENTRE REMANESCENTES DE QUILOMBO DE ATOLEIRO EM CAETÉS - PE' WHERE id=3810;
UPDATE trabalho set email_corrigido='aylla.oliveira@upe.br', titulo_corrigido='OS EFEITOS DA PANDEMIA DA COVID-19 NA SAÚDE DE ESCOLARES' WHERE id=3525;
UPDATE trabalho set email_corrigido='leticia.maciel@upe.br', titulo_corrigido='OS FATORES ASSOCIADOS A INSATISFAÇÃO CORPORAL EM JOVENS: UMA REVISÃO INTEGRATIVA DE LITERATURA ' WHERE id=3615;
UPDATE trabalho set email_corrigido='carmelitazuzart@gmail.com', titulo_corrigido='OS ÍNDIOS ANTES DE BARREIROS: O ALDEAMENTO DO UNA E A CAPITANIA DE PERNAMBUCO (1593-1742)' WHERE id=3631;
UPDATE trabalho set email_corrigido='diego.luiz@upe.br', titulo_corrigido='OS SONS DA COLÔNIA: PRÁTICAS MUSICAIS NO COLÉGIO JESUÍTA DA BAHIA NO FINAL DO SÉCULO XVI' WHERE id=3769;
UPDATE trabalho set email_corrigido='maria991651697@gmail.com', titulo_corrigido='OSTEOPOROSE INDUZIDA POR GLICOCORTICÓIDES EM PACIENTES PORTADORES DE DOENÇAS INFLAMATÓRIAS INTESTINAIS' WHERE id=3469;
UPDATE trabalho set email_corrigido='mazeus_santos@hotmail.com', titulo_corrigido='PÁGINAS EM MOVIMENTO: UTILIZAÇÃO DE RECURSO DIGITAL PARA CONSCIENTIZAÇÃO DO CYBERBULLYING NAS ESCOLAS.' WHERE id=3774;
UPDATE trabalho set email_corrigido='analuizaandrade1999@gmail.com', titulo_corrigido='PAPEL DA MONITORIA EM ATENÇÃO PRIMÁRIA À SAÚDE NA FORMAÇÃO ACADÊMICA: RELATO DE EXPERIÊNCIA' WHERE id=3626;
UPDATE trabalho set email_corrigido='jusceliopsilva@hotmail.com', titulo_corrigido='PEDAGOGIA DAS COMPETÊNCIAS: ANÁLISE E CONTEXTO DE SUA APLICABILIDADE NA FORMAÇÃO PROFISSIONAL EM EDUCAÇÃO' WHERE id=3462;
UPDATE trabalho set email_corrigido='luiz.eduardoleite@upe.br', titulo_corrigido='PERCEPÇÃO DOS ESTUDANTES DE ODONTOLOGIA QUANTO À CONDUTA CLÍNICA FRENTE ÀS RECESSÕES GENGIVAIS: UMA REVISÃO INTEGRATIVA DA LITERATURA' WHERE id=3633;
UPDATE trabalho set email_corrigido='bruna.fmelo@upe.br ', titulo_corrigido='PERCEPÇÃO E ANÁLISE DE COMPOSTOS TÓXICOS DE PLANTAS MEDICINAIS DO CASTAINHO - PE' WHERE id=3816;
UPDATE trabalho set email_corrigido='quiteriasouza57@gmail.com', titulo_corrigido='PERCEPÇÃO SOCIOAMBIENTAL NA EDUCAÇÃO BÁSICA TENDO COMO PRESSUPOSTO TEÓRICO METODOLÓGICO O MAPEAMENTO PARTICIPATIVO' WHERE id=3721;
UPDATE trabalho set email_corrigido='jocastra.cardoso@upe.br', titulo_corrigido='PERCEPÇÕES DE MONITORIA NO ESTÁGIO OBRIGATÓRIO: CONTRIBUIÇÕES PARA A FORMAÇÃO INICIAL' WHERE id=3775;
UPDATE trabalho set email_corrigido='arthurlucas-g@hotmail.com', titulo_corrigido='PERCEPÇÕES, CRENÇAS E MEDIDAS DE ENFRENTAMENTO DA DOR DE PORTADORES DE DORES CRÔNICAS NA ATENÇÃO BÁSICA À SAÚDE' WHERE id=3539;
UPDATE trabalho set email_corrigido='liviasfra@gmail.com', titulo_corrigido='PERFIL CLÍNICO EPIDEMIOLÓGICO DOS PACIENTES ACOMETIDOS PELA COVID-19 PORTADORES DE ASMA NO AMBULATÓRIO PEDIÁTRICO' WHERE id=3709;
UPDATE trabalho set email_corrigido='fnogueirarocha@gmail.com', titulo_corrigido='PERFIL DA VIOLÊNCIA HOMOFÓBICA NO ESTADO DE PERNAMBUCO' WHERE id=3621;
UPDATE trabalho set email_corrigido='nazario.goncalves@gmail.com', titulo_corrigido='PERFIL DE TRANSMISSÃO DE ANTICORPOS MATERNO-INFANTIL APÓS A VACINAÇÃO CONTRA A SARS-COV-2 EM GESTANTES' WHERE id=3708;
UPDATE trabalho set email_corrigido='sammara.correia@upe.br', titulo_corrigido='PERFIL DOS CASOS DE SÍNDROME RESPIRATÓRIA AGUDA GRAVE POR COVID-19 EM GARANHUNS/PERNAMBUCO, 2020/2021' WHERE id=3765;
UPDATE trabalho set email_corrigido='crislaine.barboza@upe.br', titulo_corrigido='PERFIL EPIDEMIOLÓGICO DA MORTALIDADE MATERNA NA XI REGIÃO DE SAÚDE DE PERNAMBUCO' WHERE id=3803;
UPDATE trabalho set email_corrigido='laizapaula6@gmail.com', titulo_corrigido='PERFIL FUNCIONAL DOS PACIENTES ACOMETIDOS POR ACIDENTES VASCULARES CEREBRAIS ADMITIDOS EM SERVIÇOS DE URGÊNCIA/EMERGÊNCIA DA MICRORREGIÃO DO PAJEÚ' WHERE id=3742;
UPDATE trabalho set email_corrigido='juliana.henrique@upe.br', titulo_corrigido='PERSPECTIVAS E DESAFIOS DA MONITORIA DE QUÍMICA GERAL E ORGÂNICA FRENTE AO ENSINO REMOTO: UM RELATO DE EXPERIÊNCIA ' WHERE id=3566;
UPDATE trabalho set email_corrigido='luciete.sousa.ufape@gmail.com', titulo_corrigido='PIBID E FORMAÇÃO DOCENTE NO ENSINO REMOTO: EXPERIÊNCIAS INTERDISCIPLINARES NO SUBPROJETO DE ALFABETIZAÇÃO E LETRAMENTO DO CURSO DE PEDAGOGIA DA UFAPE' WHERE id=3685;
UPDATE trabalho set email_corrigido='edivanjr@hotmail.com', titulo_corrigido='PLANTAS MEDICINAIS DA CAATINGA BRASILEIRA COM POTENCIAL FOTOPROTETOR ' WHERE id=3602;
UPDATE trabalho set email_corrigido='vladimir97junior@gmail.com', titulo_corrigido='PODCHEMISTRY: A UTILIZAÇÃO DO INSTAGRAM PARA A DIVULGAÇÃO CIENTÍFICA' WHERE id=3480;
UPDATE trabalho set email_corrigido='anna.sampaio@upe.br', titulo_corrigido='POLÍTICAS PÚBLICAS E MEIO AMBIENTE: UMA ANÁLISE A PARTIR DA PERCEPÇÃO DOS MORADORES DE SÃO JOSÉ DO SABUGI - PB' WHERE id=3511;
UPDATE trabalho set email_corrigido='amilson.carvalho@upe.br', titulo_corrigido='PORTFÓLIO COMO INSTRUMENTO AVALIATIVO E INCENTIVO AO DESENVOLVIMENTO DE HABILIDADES METACOGNITIVAS ' WHERE id=3491;
UPDATE trabalho set email_corrigido='anesio.marcilio@upe.br', titulo_corrigido='PORTUGUÊS BRASILEIRO: REJEIÇÃO DAS VARIANTES BRASILEIRAS E A CRENÇA DO FALAR BEM E FALAR MAL' WHERE id=3599;
UPDATE trabalho set email_corrigido='victoria.caroline@upe.br', titulo_corrigido='POSSIBILIDADES E IMPASSES DA ATUAÇÃO MULTIDISCIPLINAR NA SAÚDE MENTAL DOS TRABALHADORES DOS CENTROS DE ATENÇÃO PSICOSSOCIAL' WHERE id=3751;
UPDATE trabalho set email_corrigido='gabriella.apolinarioxavier@upe.br', titulo_corrigido='POSSÍVEIS EFEITOS ADVERSOS DA LASERTERAPIA NO TRATAMENTO DE MUCOSITE ORAL EM PACIENTES COM CÂNCER ORAL E OROFARÍNGEO' WHERE id=3628;
UPDATE trabalho set email_corrigido='glenda.sabia@upe.br', titulo_corrigido='POTENCIALIDADES E DESAFIOS DA MONITORIA ACADÊMICA NA FORMAÇÃO DO PSICÓLOGO: UM RELATO DE EXPERIÊNCIA' WHERE id=3535;
UPDATE trabalho set email_corrigido='marilia.araujo@upe.br', titulo_corrigido='POVOS INDÍGENAS DO BRASIL E TEXTOS MULTIMODAIS: UMA POSSIBILIDADE PARA RETEXTUALIZAÇÃO' WHERE id=3809;
UPDATE trabalho set email_corrigido='luiza.maia@upe.br', titulo_corrigido='PRÁTICAS DE CUIDADO PARA A MANUTENÇÃO DA INTEGRIDADE DA PELE EM IDOSOS: UMA REVISÃO LITERÁRIA' WHERE id=3456;
UPDATE trabalho set email_corrigido='joaovspereira17@gmail.com', titulo_corrigido='PRÁTICAS PROFISSIONAIS PARA O ENSINO DA MATEMÁTICA ESCOLAR: CONSTRUINDO PONTES PARA O EXERCÍCIO DA DOCÊNCIA' WHERE id=3538;
UPDATE trabalho set email_corrigido='andreza.sfreitas@upe.br', titulo_corrigido='PRECONCEITO LINGUÍSTICO: ONDE ESTÁ, COMO COMBATÊ-LO – UMA PROPOSTA DE ENSINO' WHERE id=3819;
UPDATE trabalho set email_corrigido='basiliogleyce@hotmail.com', titulo_corrigido='PREDAÇÃO DE OVINOS POR CÃES ERRANTES EM PROPRIEDADE RURAL' WHERE id=3804;
UPDATE trabalho set email_corrigido='dryelledaianne@hotmail.com', titulo_corrigido='PREVALÊNCIA DE CEFALEIA TIPO TENSÃO EM ESTUDANTES DO CURSO DE FISIOTERAPIA DE UMA FACULDADE PRIVADA DO SERTÃO DE PERNAMBUCO' WHERE id=3604;
UPDATE trabalho set email_corrigido='joana.lima@upe.br', titulo_corrigido='PREVALÊNCIA DE DOENÇA PERIODONTAL EM PACIENTES DIABÉTICOS DO MUNICÍPIO DE ARCOVERDE-PE' WHERE id=3689;
UPDATE trabalho set email_corrigido='mimaalbuquerque@yahoo.com.br', titulo_corrigido='PREVENÇÃO E ENFRENTAMENTO DA VIOLÊNCIA CONTRA A MULHER NO AMBIENTE ESCOLAR COM BASE NA LEI MARIA DA PENHA' WHERE id=3688;
UPDATE trabalho set email_corrigido='kethybarbara@gmail.com', titulo_corrigido='PRODUÇÃO DE ENZIMAS FIBRINOLÍTICAS POR COGUMELOS' WHERE id=3806;
UPDATE trabalho set email_corrigido='daiapmc@gmail.com', titulo_corrigido='PROJETO DCEXT “SANEAR PARA CUIDAR” E O AUXÍLIO DAS REDES SOCIAIS NA PARTILHA DE CONHECIMENTO SOBRE SANEAMENTO E SAÚDE EM TEMPOS DE PANDEMIA: UM RELATO DE EXPERIÊNCIA' WHERE id=3574;
UPDATE trabalho set email_corrigido='ariadny.robertta@upe.br', titulo_corrigido='PROJETO DE EXTENSÃO PRIMEIRA INFÂNCIA SAUDÁVEL: UM RELATO DE EXPERIÊNCIA' WHERE id=3725;
UPDATE trabalho set email_corrigido='lucas.honorato@upe.br', titulo_corrigido='PROJETO NETO: CUIDANDO DOS NOSSOS IDOSOS' WHERE id=3549;
UPDATE trabalho set email_corrigido='mariafernanda.filadoro@upe.br', titulo_corrigido='PROMOÇÃO DE EVENTOS ACADÊMICOS VIRTUAIS NO CENÁRIO DA PANDEMIA DA COVID-19 PELA A.A.A.M.UPEG: UM RELATO DE EXPERIÊNCIA' WHERE id=3781;
UPDATE trabalho set email_corrigido='lucas.holanda@upe.br', titulo_corrigido='PSICOLOGIA MÉDICA E A ATENÇÃO INTEGRAL À CRIANÇA EM IDADE ESCOLAR DURANTE A PANDEMIA DO NOVO CORONAVÍRUS' WHERE id=3788;
UPDATE trabalho set email_corrigido='julio.005cesar@gmail.com', titulo_corrigido='PSICOLOGIA SOCIAL, ENSINO E MONITORIA EM TEMPOS DE PANDEMIA: UM RELATO DE EXPERIÊNCIA ' WHERE id=3453;
UPDATE trabalho set email_corrigido='mvitoriadns@gmail.com', titulo_corrigido='QUALIDADE DE VIDA RELACIONADA À SAÚDE, PERCEPÇÃO DE ESTRESSE E SINTOMAS DEPRESSIVOS EM UNIVERSITÁRIOS: DADOS PRELIMINARES' WHERE id=3551;
UPDATE trabalho set email_corrigido='diego.aud@upe.br', titulo_corrigido='REABILITAÇÃO DA REGIÃO POSTERIOR DE MAXILA ATRÓFICA PELA TÉCNICA DO LEVANTAMENTO DE SEIO MAXILAR: RELATO DE CASO' WHERE id=3760;
UPDATE trabalho set email_corrigido='davysilva007@gmail.com', titulo_corrigido='READAPTAÇÃO DE PEQUENAS EMPRESAS BRASILEIRAS EM MEIO A PANDEMIA DE COVID-19' WHERE id=3451;
UPDATE trabalho set email_corrigido='luan.nilton1@gmail.com', titulo_corrigido='REAPROVEITAMENTO DO RESÍDUO DE CAFÉ PARA PRODUÇÃO DE PROTEASES UTILIZANDO O FUNGO ASPERGILLUS OCHRACEUS POR MEIO DA FERMENTAÇÃO EM ESTADO SÓLIDO ' WHERE id=3548;
UPDATE trabalho set email_corrigido='yanipacheco80@gmail.com', titulo_corrigido='REBILITAÇÃO VISUAL NO VIRTUAL EM TEMPOS DE PANDEMIA: RELATO DE EXPERIÊNCIA' WHERE id=3589;
UPDATE trabalho set email_corrigido='wanessa.alessandra@yahoo.com.br', titulo_corrigido='REFLEXÕES SOBRE MATRICIAMENTO DO CENTRO DE ATENÇÃO PSICOSSOCIAL NA ATENÇÃO BÁSICA EM UMA CIDADE DO INTERIOR PERNAMBUCANO' WHERE id=3439;
UPDATE trabalho set email_corrigido='pedro.alexandre@upe.br', titulo_corrigido='REFLEXÕES SOBRE O TOTALITARISMO A PARTIR DE UM DIÁLOGO ENTRE AS IDEIAS DE JACQUES MARITAIN E HANNAH ARENDT. ' WHERE id=3662;
UPDATE trabalho set email_corrigido='mariaabath.campos@upe.br', titulo_corrigido='RELATO DE EXPERIÊNCIA - DISCIPLINA CURRICULAR DE EXTENSÃO : O SANEAMENTO E OS ASPECTOS DA SAÚDE PÚBLICA QUE O CONSTITUEM' WHERE id=3823;
UPDATE trabalho set email_corrigido='jhenyffer.lays@upe.br', titulo_corrigido='RELATO DE EXPERIÊNCIA DE MONITORIA NA DISCIPLINA HISTÓRIA DA PSICOLOGIA: DESAFIOS DO ENSINO-APRENDIZAGEM DE FORMA REMOTA' WHERE id=3744;
UPDATE trabalho set email_corrigido='sidney.alves@upe.br', titulo_corrigido='RELATO DE EXPERIÊNCIA EM CAMPO DE ESTÁGIO ESCOLAR: OS ESTUDOS E A IMPORTÂNCIA DA PRÉ-HISTÓRIA NO CONHECIMENTO HISTÓRICO ' WHERE id=3496;
UPDATE trabalho set email_corrigido='nandoaciole@hotmail.com', titulo_corrigido='RELATO DE EXPERIÊNCIA NA MONITORIA NO ENSINO DO ACONSELHAMENTO PSICOLÓGICO' WHERE id=3738;
UPDATE trabalho set email_corrigido='eduarda.albuquerquem@upe.br', titulo_corrigido='RELATO DE EXPERIÊNCIAS DAS ATIVIDADES E AÇÕES DA DISCIPLINA CURRICULAR DE EXTENSÃO, EM TEMPOS PANDÊMICOS, COM FOCO NA TEMÁTICA ÁGUA NO MUNICÍPIO DE GARANHUNS' WHERE id=3595;
UPDATE trabalho set email_corrigido='hermelanyantunes@gmail.com', titulo_corrigido='RESSIGNIFICANDO PROMOÇÃO DE SAÚDE MENTAL NA PANDEMIA' WHERE id=3729;
UPDATE trabalho set email_corrigido='marcelle.cabral@upe.br', titulo_corrigido='RESSONÂNCIAS DA MONITORIA: O JOGO TRILHA NO ENSINO REMOTO' WHERE id=3461;
UPDATE trabalho set email_corrigido='patricia.cavalcante@upe.br', titulo_corrigido='REVISANDO CONCEITOS E ASSUNTOS DE IMUNOLOGIA DEPOSITADOS NA ENCICLOPEDIA VIRTUAL WIKIPEDIA' WHERE id=3454;
UPDATE trabalho set email_corrigido='victoria.caroline@upe.br', titulo_corrigido='RODAS DE CONVERSA - UM CAMINHAR APRENDENTE: PROMOÇÃO DE SAÚDE A TRABALHADORES(AS) E ESTUDANTES' WHERE id=3731;
UPDATE trabalho set email_corrigido='eduarda.josianebraga@upe.br', titulo_corrigido='SABERES E EXPERIÊNCIAS: MULHERES INDÍGENAS KAPINAWÁ E A SIGNIFICAÇÃO NARRATIVA DO RECONHECIMENTO  ' WHERE id=3524;
UPDATE trabalho set email_corrigido='michael-alb@hotmail.com', titulo_corrigido='SALA DE AULA INVERTIDA NO ENSINO DA MATEMÁTICA.' WHERE id=3455;
UPDATE trabalho set email_corrigido='thamires.rafaela@upe.br', titulo_corrigido='SAÚDE MENTAL E CONTEXTO LABORAL: A SITUAÇÃO DAS EQUIPES MULTIPROFISSIONAIS DA MESORREGIÃO DO AGRESTE PERNAMBUCANO' WHERE id=3673;
UPDATE trabalho set email_corrigido='barbara.siqueira@upe.br', titulo_corrigido='SENTIDOS ATRIBUÍDOS À PRÁTICA DE MUSCULAÇÃO POR ESTUDANTES UNIVERSITÁRIOS' WHERE id=3654;
UPDATE trabalho set email_corrigido='paula.siqueira@upe.br', titulo_corrigido='SENTIDOS DO MEDO E CUIDADO ATRIBUÍDOS À PRÁTICA DE ATIVIDADE FÍSICA DURANTE A PANDEMIA' WHERE id=3576;
UPDATE trabalho set email_corrigido='naraitlas@gmail.com', titulo_corrigido='SENTIDOS SOBRE A CONDICIONALIDADE DA EDUCAÇÃO: PERSPECTIVAS A PARTIR DO PROGRAMA BOLSA FAMÍLIA' WHERE id=3683;
UPDATE trabalho set email_corrigido='thaisfaustino00@gmail.com', titulo_corrigido='SEQUÊNCIA LÚDICA SOBRE A IMPORTÂNCIA DAS ABELHAS: UMA POSSIBLIDADE EDUCATIVA NAS SÉRIES INICIAIS' WHERE id=3579;
UPDATE trabalho set email_corrigido='kessia_luiza@outlook.com', titulo_corrigido='SÍFILIS GESTACIONAL E SÍFILIS CONGÊNITA: UMA REVISÃO DE LITERATURA' WHERE id=3583;
UPDATE trabalho set email_corrigido='luiza.ferreirasilva@upe.br', titulo_corrigido='SIGNIFICANTES E SENTIDOS DA MONITORIA EM VIDA ACADÊMICA DE MONITORAS' WHERE id=3713;
UPDATE trabalho set email_corrigido='suellenjnsan@gmail.com', titulo_corrigido='SILENCIADAS: MULHERES COMO SUJEITO HISTÓRICO E POLÍTICO NO PROCESSO DE REDEMOCRATIZAÇÃO BRASILEIRO' WHERE id=3458;
UPDATE trabalho set email_corrigido='ruantrindade14@gmail.com', titulo_corrigido='SÍNDROME DE BRUGADA: UMA ANÁLISE ELETROCARDIOGRÁFICA' WHERE id=3473;
UPDATE trabalho set email_corrigido='enauanny@gmail.com', titulo_corrigido='SINDROME DE BURNOUT: SINTOMATOLOGIA E TRATAMENTO' WHERE id=3520;
UPDATE trabalho set email_corrigido='wesleytsilva.ufpe@gmail.com', titulo_corrigido='SUSCEPTIBILIDADE ANTIMICROBIANA DAS INFECÇÕES DO TRATO URINÁRIO EM MULHERES ASSISTIDAS NA ATENÇÃO BÁSICA DE CARUARU' WHERE id=3434;
UPDATE trabalho set email_corrigido='pedagogoleandro@outlook.com', titulo_corrigido='SUSTENTABILIDADE E ESTRATÉGIAS DE CONSCIENTIZAÇÃO AMBIENTAL EM ESCOLAS PÚBLICAS: DESAFIOS E AVANÇOS DO MUNICÍPIO DE SÃO JOSÉ DO SABUGI.' WHERE id=3522;
UPDATE trabalho set email_corrigido='samarasantana2211@gmail.com', titulo_corrigido='TÂMARAS DO MUTIRÃO: A EXTENSÃO UNIVERSITÁRIA COMO AGENTE TRANSFORMADOR DA EDUCAÇÃO EM SAÚDE INFANTIL' WHERE id=3542;
UPDATE trabalho set email_corrigido='thatiany.ferreira@upe.br', titulo_corrigido='TECNOLOGIAS DIGITAIS E A EDUCAÇÃO MATEMÁTICA: UM ESTUDO DE FRAÇÃO NO LIVRO DIDÁTICO DIGITAL MATHIGON' WHERE id=3459;
UPDATE trabalho set email_corrigido='eduardo1722silva@gmail.com', titulo_corrigido='TECNOLOGIAS NO ENSINO DE GEOGRAFIA EM TEMPOS DE PANDEMIA: UMA EXPERIÊNCIA COM PODCASTS NO PROGRAMA RESIDÊNCIA PEDAGÓGICA – APONTAMENTOS INICIAIS' WHERE id=3808;
UPDATE trabalho set email_corrigido='isabel.almeida@upe.br', titulo_corrigido='TERAPIA COGNITIVA COMPORTAMENTAL NOS TRANSTORNOS ALIMENTARES EM ADOLESCENTES: UMA REVISÃO INTEGRATIVA' WHERE id=3750;
UPDATE trabalho set email_corrigido='leonardo.pbsouza@upe.br', titulo_corrigido='TERAPIA COGNITIVO-COMPORTAMENTAL E AS INTERFACES ENTRE O TRANSTORNO DE ESTRESSE PÓS-TRAUMÁTICO E O USO DE ÁLCOOL' WHERE id=3652;
UPDATE trabalho set email_corrigido='sara.maciel@upe.br', titulo_corrigido='TERAPIA COGNITIVO-COMPORTAMENTAL NO TRATAMENTO DO TRANSTORNO DE COMPULSÃO ALIMENTAR: UMA REVISÃO DE LITERATURA' WHERE id=3501;
UPDATE trabalho set email_corrigido='danialencararaujo@outlook.com', titulo_corrigido='TERAPIAS ADJUVANTES PARA O TRATAMENTO CIRÚRGICO DAS RECESSÕES GENGIVAIS: UMA REVISÃO NARRATIVA DA LITERATURA. ' WHERE id=3526;
UPDATE trabalho set email_corrigido='Fellipe.melo@hotmail.com', titulo_corrigido='TETRALOGIA DE FALLOT: UMA REVISÃO DE LITERATURA DOS SEUS PRINCIPAIS ASPECTOS' WHERE id=3797;
UPDATE trabalho set email_corrigido='marcos.viniciuscorreia@upe.br', titulo_corrigido='TRADICIONALISMO EM CRISE: NOVAS PERSPECTIVAS DO FORRÓ.' WHERE id=3618;
UPDATE trabalho set email_corrigido='mariliassantana13@gmail.com', titulo_corrigido='TRAJETÓRIA, ACESSO E PERMANÊNCIA DE ESTUDANTES COTISTAS NO ENSINO SUPERIOR: UM ESTUDO DE CASO NO CURSO DE DIREITO DA UNIVERSIDADE DE PERNAMBUCO – CAMPUS ARCOVERDE. ' WHERE id=3513;
UPDATE trabalho set email_corrigido='lucia.beatriz@upe.br', titulo_corrigido='TRANSPLANTE DE ÓRGÃOS: UMA ANÁLISE HISTÓRICA' WHERE id=3573;
UPDATE trabalho set email_corrigido='gustavo.leiteoliveira@upe.br', titulo_corrigido='TRANSTORNO DE ANSIEDADE GENERALIZADA: O TRATAMENTO PELA TERAPIA COGNITIVA COMPORTAMENTAL' WHERE id=3624;
UPDATE trabalho set email_corrigido='fabio.andrey@upe.br', titulo_corrigido='TRANSTORNOS TEMPOROMANDIBULARES EM PACIENTES COM DEFORMIDADE DENTOESQUELÉTICA E PERFIL FACIAL CLASSE II: UM ESTUDO EPIDEMIOLÓGICO' WHERE id=3753;
UPDATE trabalho set email_corrigido='analeticia.melo@gmail.com', titulo_corrigido='TRANSVERGENTE' WHERE id=3714;
UPDATE trabalho set email_corrigido='lucasnunes932@gmail.com', titulo_corrigido='TRANSVERGENTE: UMA ANÁLISE JURÍDICO-SOCIAL SOBRE ALGUNS DOS IMPACTOS DA TRANSPOSIÇÃO DO RIO SÃO FRANCISCO NAS COMUNIDADES CAMPONESAS NO MUNICÍPIO DE SERTÂNIA-PE' WHERE id=3733;
UPDATE trabalho set email_corrigido='elidiane.reges@upe.br', titulo_corrigido='TRILHAS DO CUIDADO: O USO DE PODCASTS COMO ESTRATÉGIA DE PROMOÇÃO DE CUIDADO E SAÚDE MENTAL PARA TRABALHADORES/AS' WHERE id=3695;
UPDATE trabalho set email_corrigido='gregoriodantas@hotmail.com', titulo_corrigido='TUMOR DE PANCOAST: A IMPORTÂNCIA DO DIAGNÓSTICO PRECOCE' WHERE id=3724;
UPDATE trabalho set email_corrigido='baltebezerra@gmail.com', titulo_corrigido='ULTILIZAÇÃO DE RHBMP-2 NA RECONSTRUÇÃO ÓSSEA EM ÁREA ESTÉTICA RELATO DE CASO' WHERE id=3650;
UPDATE trabalho set email_corrigido='maria.ercilialimabarreiro@gmail.com', titulo_corrigido='ULTRASSOM DE BAIXA FREQUÊNCIA NA EFICIÊNCIA CATALITICA DE ENZIMAS PRODUZIDAS POR FUNGOS: UMA REVISÃO DE LITERATURA.' WHERE id=3593;
UPDATE trabalho set email_corrigido='claudeaneferreira2000@hotmail.com', titulo_corrigido='UM ESTUDO SOBRE A VARIAÇÃO DO USO DE NÓS E A GENTE NA FALA DE MORADORES DE JUCATI-PE' WHERE id=3783;
UPDATE trabalho set email_corrigido='ingridjvieira@gmail.com', titulo_corrigido='UM PÉ DE SAÚDE' WHERE id=3698;
UPDATE trabalho set email_corrigido='marquesgilmara930@gmail.com', titulo_corrigido='UMA ANÁLISE SOBRE PLANEJAMENTO ESCOLAR E SABERES DOCENTE: RELATO DE PROFESSORAS DA EDUCAÇÃO INFANTIL NO CONTEXTO DE PANDEMIA' WHERE id=3446;
UPDATE trabalho set email_corrigido='edsonjose355@gmail.com', titulo_corrigido='UMA HISTÓRIA REPUBLICANA NO BRASIL: USOS E CONCEITOS (1789-1845)' WHERE id=3470;
UPDATE trabalho set email_corrigido='estefane.melo@upe.br', titulo_corrigido='USO ABUSIVO DE MEDICAMENTOS BENZODIAZEPÍNICOS: UMA ANÁLISE DA SAÚDE MENTAL E DOS ASPECTOS SOCIOECONÔMICOS EM UMA COMUNIDADE QUILOMBOLA DO AGRESTE PERNAMBUCANO' WHERE id=3493;
UPDATE trabalho set email_corrigido='thalianog7@gmail.com', titulo_corrigido='USO DA PELE DE TILÁPIA DO NILO COMO MEDIDA ALTERNATIVA NO CUIDADO DE PACIENTES VÍTIMAS DE QUEIMADURA' WHERE id=3503;
UPDATE trabalho set email_corrigido='yasmin.britto@upe.br', titulo_corrigido='USO DA PROBLEMATIZAÇÃO EM GRUPOS DE ESTUDO SOBRE DENTÍSTICA OPERATÓRIA' WHERE id=3771;
UPDATE trabalho set email_corrigido='camillacynara0@gmail.com', titulo_corrigido='USO DE METODOLOGIAS ATIVAS PARA CONSTRUÇÃO DO CONHECIMENTO NA DISCIPLINA DE ANATOMIA HUMANA: UM RELATO DE EXPERIÊNCIA' WHERE id=3534;
UPDATE trabalho set email_corrigido='leticia.saldanha@upe.br', titulo_corrigido='USO DE MORFINA NA REDUÇÃO DA DOR EM PACIENTES TERMINAIS' WHERE id=3656;
UPDATE trabalho set email_corrigido='daniel.medeirosnunes@upe.br', titulo_corrigido='USO DE PLANTAS MEDICINAIS POR MULHERES GESTANTES: UMA REVISÃO DE LITERATURA' WHERE id=3822;
UPDATE trabalho set email_corrigido='mariana.vsarruda@upe.br', titulo_corrigido='USO DE RECURSOS TECNOLÓGICOS E INOVAÇÕES METODOLÓGICAS NO PROCESSO DE ENSINO-APRENDIZAGEM DA EMBRIOLOGIA E FISIOLOGIA HUMANA NO MÓDULO MORFOFUNCIONAL NA GRADUAÇÃO EM MEDICINA – RELATO DE EXPERIÊNCIA' WHERE id=3606;
UPDATE trabalho set email_corrigido='renata.aline@upe.br', titulo_corrigido='USO DE TECNOLOGIA DA INFORMAÇÃO E COMUNICAÇÃO NO GERENCIAMENTO FINANCEIRO DE PEQUENOS EMPREENDIMENTOS RURAIS NA MICRORREGIÃO DE SALGUEIRO' WHERE id=3679;
UPDATE trabalho set email_corrigido='lucas.ysilva@upe.br', titulo_corrigido='UTILIZAÇÃO DA CASCA DE CAMARÃO SOSSEGO (MACROBRACHIUM JELSKII, MIERS 1877) PARA EXTRAÇÃO DE QUITINA E SUA IMPORTÂNCIA COMO FORMA DE AGREGAR VALOR À ESPÉCIE' WHERE id=3761;
UPDATE trabalho set email_corrigido='eduarda.cavalcantia@upe.br', titulo_corrigido='UTILIZAÇÃO DE PLANEJAMENTO VIRTUAL E CIRURGIA GUIADA PARA REABILITAÇÃO DE MAXILA ATRÓFICA' WHERE id=3784;
UPDATE trabalho set email_corrigido='larih1carla@gmail.com', titulo_corrigido='VALORIZAÇÃO DA GALACTOMANANA EXTRAÍDA DA CASSIA GRANDIS COMO ADITIVO DE IOGURTES ' WHERE id=3545;
UPDATE trabalho set email_corrigido='djaelmartins@gmail.com', titulo_corrigido='VENTO, AREIA E AMORAS BRAVAS: A ESCRITA FRAGMENTADA E A VOZ FEMININA EM AGUSTINA BESSA-LUÍS' WHERE id=3505;
UPDATE trabalho set email_corrigido='henrique.bernardo@upe.br', titulo_corrigido='VERDADE OU MENTIRA? DILEMAS DA PÓS-VERDADE' WHERE id=3584;
UPDATE trabalho set email_corrigido='socorro_clementino@hotmail.com', titulo_corrigido='VIGILÂNCIA GENÔMICA DO SARS-COV-2: UMA PREOCUPAÇÃO MUNDIAL' WHERE id=3755;
UPDATE trabalho set email_corrigido='wanessa.alessandra@yahoo.com.br', titulo_corrigido='VIVÊNCIAS SOBRE ATENDIMENTO PSICOLÓGICO ONLINE DURANTE A PANDEMIA DO NOVO CORONAVÍRUS POR UMA REDE MUNICIPAL ' WHERE id=3450;
